### ISSUE TITLE
Deliverable and bullet point

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#101]
When in MONARC we set a list (bullet point) in a text area, and then export a deliverable. The bullet point is not a bullet point but it continues the numbering of the deliverable.

**Comment by cedricbonhomme** [comment]
WIP monarc-project/zm-client@ba85a9e6dbfc7ac50cfb8600fadeca3c7111b2

**Comment by cedricbonhomme** [comment]
Seems to be OK now.
monarc-project/zm-client@edf617eeabf883e55e313a04c7ec8ddbd8198a31
monarc-project/zm-client@9a55f0d49c4af0cdce856e1b6ab84d5ab0312925
