### ISSUE TITLE
Sort order for operational risks in final deliverable annex D

### ISSUE THREAD

**Issue by ThierryPGT** [monarc-project/MonarcAppFO#111]
The current order for operational risks is very difficult to understand, no real logic.

For GDPR compliance rapport, it would be very usefull to order the table as the assets appear in the risk analysis,"For example :
![capture](https://user-images.githubusercontent.com/26403448/42763525-9e684b2c-8913-11e8-89f1-9fd4c43d2ba8.JPG)

In this case it would be : 
Gouvernance
DPO
Licéité et légitimité
Consentement
Intérêt légitime
Droit à l'information
..

Thanks in advance
Thierry

**Comment by jerolomb** [comment]
In fact there is a logic. It's the following : The sort is on the MAX risk (to avoid scrolling in case of risks are not evaluated), so for exemple if you have the "Droit à la limitation du traitement" which have the highest value in its risk. It will be first in the table. 

As the sort is at least than describe above or is there a bug ? 

So we ll study your request.

**Comment by ThierryPGT** [comment]
Ok I undestand.
It's not a bug at all.
The annex A is the only proof, where you can find consultant notes.
If there is some risks not evaluated, I think (now) that they must appear in the Deliverable. because it's a choice.
I think that, if there no other reasons to sort Max --> Min 
The order of risks in the analysis as sense. For GRPD, when you want to see all risks for a treatment the only way is to cut and copy data in the annex A. If the order is the same of the analysis, it's become very easy.

**Comment by ThierryPGT** [comment]
Another thing is the same range.
If you export risk-op in csv, it's the same problem
![capture](https://user-images.githubusercontent.com/26403448/42986518-1cec414e-8bf6-11e8-9b64-0dd1bc521631.JPG)
It this case, it's better to insert the whole path of object to know the hierarchical structure
CU
Thierry

**Comment by jfrocha** [comment]
We have created a new tag for operational risks ordering by Id of risk. ${TABLE_AUDIT_RISKS_OP_ORDER_BY_POSITION}

It is not by default in third deliverable, so you need customize your template.

We will check for CSV export.

Commit related : https://github.com/monarc-project/zm-client/commit/586aa45cfdeaf395a677920eb5bdeb23500a7fe6

**Comment by ThierryPGT** [comment]
Hello,
sorry but It dont work :-(
This is a basic Case
![capture](https://user-images.githubusercontent.com/26403448/44676013-625aba80-aa32-11e8-915f-f6e4bf2f5a43.JPG)
Here the first page of the deliverable :
![capture](https://user-images.githubusercontent.com/26403448/44676100-93d38600-aa32-11e8-919f-8db553b648be.JPG).

Here the json file if jour want to test : 

Thanks in advance
CU

Thierry

**Comment by jfrocha** [comment]
We improved sort order of operational risks.
The Tag ${TABLE_AUDIT_RISKS_OP_ORDER_BY_POSITION} is not longer use.
Get back to default tag.
[Commit related](https://github.com/monarc-project/zm-client/commit/bb181811fd6c6200f2e237ea391c0fe08f1f62a3)

**Comment by jfrocha** [comment]
FIX some issue with the order of the table
https://github.com/monarc-project/zm-client/commit/3f72b5e85d1f905476a87a64e1fd1eac3aa88a87
