### ISSUE TITLE
Documentation on platform and application security of Monarc components

### ISSUE THREAD

**Issue by PeterGeelen** [monarc-project/MonarcAppFO#120]
Documentation on the security features of the platform
- which security features are available in the platform
- what methods and techniques are used during design, build & operations of the platform...
- how are platform / function components isolated (to a void lateral movement of a hacker)
- use of SDLC

Do you have any information on the platform and application security of Monarc?

We had a few questions from our 'customers' (fed. Gov depts…) on the security of the hosted Monarc platform in relation to the overall security.
And as part of the FAQ and support of the system at the Chancellerie we would like to provide some info to the departments.

What security features have been built-in in Monarc?
Do you have documentation on 
-	Infra security
-	Application security
-	Interface security
-	…

Have you tested the platform for external threats, pen testing?
What security design methodology has been used to develop Monarc?

**Comment by cedricbonhomme** [comment]
Sorry for the response delay. In fact we recently decided to provide some more information regarding this aspect, especially for Chancellerie and CCB. The document will be public and address the points:

- security design choices (isolation of different MONARC components);
- application security (the code itself);
- web interface security.

Concerning documentation, we already provide information about the software MONARC and 
about the typical architecture[1] deployed when a back office is used with MONARC.

We won't provide that much recommendations for the architecture of the self-hosted product and the "operations of the platform". We will simply give some good tips based on our experience and the security features we have put in place for our service[2]. MONARC administrators are free to put in place their security measures  (based on corporate requirements, etc).

If you are interested in the key future developments you can check the roadmap[3]. We try to stick to a pragmatic roadmap without crazy long-term view...

We do not have formal pen testing report. But we know that come company (and of course us) are testing MONARC. We already got some feedback in the past. You can see here[4] our vulnerability disclosure policy.

[1] https://www.monarc.lu/documentation/technical-guide/#architecture
[2] https://my.monarc.lu
[3] https://github.com/monarc-project/MonarcAppFO/wiki/Roadmap
[4] https://www.monarc.lu/community/vulnerability-disclosure/

**Comment by jfrocha** [comment]
Cf. documentation 
https://www.monarc.lu/documentation/security-considerations/
