### ISSUE TITLE
Issue opening Final Report in LibreOffice

### ISSUE THREAD

**Issue by PaoloVecchi** [monarc-project/MonarcAppFO#127]
While I'm able to open correctly (as usual) docx files generated for the other reports the Final Risk Assessment report opens but after it displays the following error:

> An error occurred during opening the file. This may be caused by incorrect file contents.
> The error details are:
> SAXException: [word/document.xml line 78]: unknown error
> Proceeding with import may cause data loss or corruption, and application may become unstable or crash.

By cancelling the operation it comes up with these additional info:

> File format error found at Wrong relinfo stream!
> SAXParseException: '[word/document.xml line 78]: unknown error', Stream 'word/document.xml', Line 78, Column 2164(row,col).

In that section of the XML I haven't been able to identify the tags that can cause the error.

The document seems to get truncated after the Risk Treatment scale in section 1.2, no more pages/content after that even if the template contains additional pages.

Tested with both LibreOffice 5.7 and 6.10.
Unlikely to be a LibreOffice bug (searched around and found no related bugs), it seems to be an issue with the document generation.

I wanted to do an additional test by loading an edited template which replaces proprietary fonts with commonly available ones, uploaded, selected it when generating the report but it still presents me with the usual standard document. (maybe a bug?)

**Comment by cedricbonhomme** [comment]
There should be a problem with this file. Thanks, we'll check that.

**Comment by PaoloVecchi** [comment]
I confirm the issue with the corrupt template file.

I've created a French analysis, which uses a different template, and the document opened without issue.

**Comment by jfrocha** [comment]
Fixed on https://github.com/monarc-project/MonarcAppFO/commit/5e48ed46654d594320c37781d05a9d7e2ad5bbe8
