### ISSUE TITLE
Reports not generated in user's language or selected templates

### ISSUE THREAD

**Issue by PaoloVecchi** [monarc-project/MonarcAppFO#129]
User's language doesn't seems to be taken in consideration when generating deliverables as they are always in English.

Even by creating a custom template in French and selecting it to generate the documents the resulting document is still the standard English one.

Tested with OVA VM version 2.7.0

**Comment by cedricbonhomme** [comment]
The language of the template depends of the language of the analysis, not of the language of the user profile (the language of the Web user interface).
This is the answer to your question in #127 when you tried to use your custom template.

Technically it shouldn't be a problem to select a template based on the user profile. The only thing, is that you may have for example some parts of the template in English and some parts in French.

**Comment by PaoloVecchi** [comment]
I've created a new analysis in French and it shows the French template as expected.

The issue I still see is that if I select a custom template it ignores my selection and it just uses the standard template.

Apart from the language issue, common to switch between English and French here in Luxembourg, is that it seems that the drop down menu selection is being ignored.
