### ISSUE TITLE
Add a confirmation message before deleting a risk analysis

### ISSUE THREAD

**Issue by didierbarzin** [monarc-project/MonarcAppFO#138]
Yes I have made that ...

**Comment by cedricbonhomme** [comment]
There should be a configuration message.
Which browser are you using?

**Comment by cedricbonhomme** [comment]
OK, so this is on a bit old MONARC version. You can update it:
https://www.monarc.lu/documentation/technical-guide/#update-a-single-monarc-instance

We are not able to reproduce the bug with MONARC>=2.6.0. Not testes before.

**Comment by didierbarzin** [comment]
Fixed, thanks.
Could you update the Monarc_demo VM ?

**Comment by cedricbonhomme** [comment]
We are providing a new virtual machine for each latest releases:
https://github.com/monarc-project/MonarcAppFO/releases/latest
