### ISSUE TITLE
Improve risk sheet screen

### ISSUE THREAD

**Issue by didierbarzin** [monarc-project/MonarcAppFO#139]
I have spent a lot of time navigating throw screens in Monarc to enter the measures in place. 
In the risk sheet screen, is it possible to :
- Allow to modify the measures in place and the qualification of the vulnerability
- Allow to go to the next risk, previous by following the list of risks of the previous screen (if the user comes from this screen)
- when returning to the risk list, the position in the list is lost: page number, number of lines per page and the filter.

Thanks,
Didier

![untitled](https://user-images.githubusercontent.com/43208232/45818679-ba5ba880-bce2-11e8-975b-3b8bc56c724b.png)

**Comment by jfrocha** [comment]
[Partial fix keeping filters on go back risk list](https://github.com/monarc-project/ng-anr/commit/2555c065eadda094e68181fa2d89cf5ede509644)
