### ISSUE TITLE
Import of risk analysis failed on version 2.7.1

### ISSUE THREAD

**Issue by eromang** [monarc-project/MonarcAppFO#140]
Dear Monarc team,

In version 2.7.1, import of an risk analysis under Safari 12 Mac OS X 10.14, will lead to an error message that the import file is not existing. Same on Firefox for Mac version 

![ericromang 2018-10-05 at 14 20 29](https://user-images.githubusercontent.com/545923/46534982-41e01480-c8aa-11e8-85ed-30374a52657d.png)

**Comment by cedricbonhomme** [comment]
Hi,
thank you for the report. Could you please share the error you got in the browser's console, like the error sent from the backend.
It is only on a specific analysis? If yes, in which language ?

**Comment by cedricbonhomme** [comment]
It can be a problem of file size.
You can try to update the file /etc/php/7.1/apache2/php.ini like this:
https://github.com/monarc-project/MonarcAppFO/blob/master/vagrant/bootstrap.sh#L24

**Comment by cedricbonhomme** [comment]
It can be a problem of file size.
You can try to update the file /etc/php/7.1/apache2/php.ini like this:
https://github.com/monarc-project/MonarcAppFO/blob/master/vagrant/bootstrap.sh#L24

**Comment by eromang** [comment]
Dear @cedricbonhomme I use the virtual machine. Here we go for the browser console error.
<img width="1438" alt="ericromang 2018-10-12 at 15 07 35" src="https://user-images.githubusercontent.com/545923/46871094-baa61a00-ce30-11e8-9505-5e47992e7201.png">

**Comment by cedricbonhomme** [comment]
I think its probably linked to a problem of file size.

Which VM do you have downloaded? A recent one? For 'older' VMs I am not sure that we have defined the adequate settings in the PHP configuration file (https://github.com/monarc-project/MonarcAppFO/blob/master/vagrant/bootstrap.sh#L19).  You should check these values.
Or maybe you can try to import your analysis in the VM of the version 2.7.2 of MONARC (https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.7.2).


The other strange thing I see on your screen shot (but not linked to this problem) is the problem with the missing files: nv.d3.min.css.map and forge.min.js.map.
Running an update (https://www.monarc.lu/documentation/technical-guide/#update-a-single-monarc-instance) should fix these problems.
