### ISSUE TITLE
Error loading risk analysis in my.monarc.lu

### ISSUE THREAD

**Issue by sarah-peter** [monarc-project/MonarcAppFO#144]
My collegue and I have several risk analyses in the online version on https://my.monarc.lu. We discovered today that the data doesn't get loaded when we open any of those analyses. The loading symbol keeps turning and several red error boxes pop up on the right side of the screen with error messages like

> An error occurred while fetching api/client-anr/1/soa: An exception occurred while executing 'SELECT t0.id AS id_1, t0.code AS code_2, t0.label1 AS label1_3, t0.label2 AS label2_4, t0.label3 AS label3_5, t0.label4 AS label4_6, t0.status AS status_7, t0.creator AS creator_8, t0.created_at AS created_at_9, t0.updater AS updater_10, t0.updated_at AS updated_at_11, t0.anr_id AS anr_id_12, t0.soacategory_id AS soacategory_id_13 FROM measures t0 WHERE t0.id = ?' with params [1]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.label1' in 'field list' (500)

or

> An error occurred while fetching api/client-anr/1/amvs: An exception occurred while executing 'SELECT a0_.id AS id_0, a0_.position AS position_1, a0_.status AS status_2, a0_.creator AS creator_3, a0_.created_at AS created_at_4, a0_.updater AS updater_5, a0_.updated_at AS updated_at_6, a1_.id AS id_7, a1_.label1 AS label1_8, a1_.label2 AS label2_9, a1_.label3 AS label3_10, a1_.label4 AS label4_11, a1_.description1 AS description1_12, a1_.description2 AS description2_13, a1_.description3 AS description3_14, a1_.description4 AS description4_15, a1_.status AS status_16, a1_.mode AS mode_17, a1_.type AS type_18, a1_.code AS code_19, a1_.creator AS creator_20, a1_.created_at AS created_at_21, a1_.updater AS updater_22, a1_.updated_at AS updated_at_23, t2_.id AS id_24, t2_.label1 AS label1_25, t2_.label2 AS label2_26, t2_.label3 AS label3_27, t2_.label4 AS label4_28, t2_.description1 AS description1_29, t2_.description2 AS description2_30, t2_.description3 AS description3_31, t2_.description4 AS description4_32, t2_.status AS status_33, t2_.mode AS mode_34, t2_.code AS code_35, t2_.trend AS trend_36, t2_.qualification AS qualification_37, t2_.c AS c_38, t2_.i AS i_39, t2_.a AS a_40, t2_.comment AS comment_41, t2_.creator AS creator_42, t2_.created_at AS created_at_43, t2_.updater AS updater_44, t2_.updated_at AS updated_at_45, v3_.id AS id_46, v3_.label1 AS label1_47, v3_.label2 AS label2_48, v3_.label3 AS label3_49, v3_.label4 AS label4_50, v3_.description1 AS description1_51, v3_.description2 AS description2_52, v3_.description3 AS description3_53, v3_.description4 AS description4_54, v3_.status AS status_55, v3_.mode AS mode_56, v3_.code AS code_57, v3_.creator AS creator_58, v3_.created_at AS created_at_59, v3_.updater AS updater_60, v3_.updated_at AS updated_at_61, m4_.id AS id_62, m4_.code AS code_63, m4_.label1 AS label1_64, m4_.label2 AS label2_65, m4_.label3 AS label3_66, m4_.label4 AS label4_67, m4_.status AS status_68, m4_.creator AS creator_69, m4_.created_at AS created_at_70, m4_.updater AS updater_71, m4_.updated_at AS updated_at_72, m5_.id AS id_73, m5_.code AS code_74, m5_.label1 AS label1_75, m5_.label2 AS label2_76, m5_.label3 AS label3_77, m5_.label4 AS label4_78, m5_.status AS status_79, m5_.creator AS creator_80, m5_.created_at AS created_at_81, m5_.updater AS updater_82, m5_.updated_at AS updated_at_83, m6_.id AS id_84, m6_.code AS code_85, m6_.label1 AS label1_86, m6_.label2 AS label2_87, m6_.label3 AS label3_88, m6_.label4 AS label4_89, m6_.status AS status_90, m6_.creator AS creator_91, m6_.created_at AS created_at_92, m6_.updater AS updater_93, m6_.updated_at AS updated_at_94, a0_.anr_id AS anr_id_95, a0_.asset_id AS asset_id_96, a0_.threat_id AS threat_id_97, a0_.vulnerability_id AS vulnerability_id_98, a0_.measure1_id AS measure1_id_99, a0_.measure2_id AS measure2_id_100, a0_.measure3_id AS measure3_id_101, a1_.anr_id AS anr_id_102, t2_.anr_id AS anr_id_103, t2_.theme_id AS theme_id_104, v3_.anr_id AS anr_id_105, m4_.anr_id AS anr_id_106, m4_.soacategory_id AS soacategory_id_107, m5_.anr_id AS anr_id_108, m5_.soacategory_id AS soacategory_id_109, m6_.anr_id AS anr_id_110, m6_.soacategory_id AS soacategory_id_111 FROM amvs a0_ INNER JOIN assets a1_ ON a0_.asset_id = a1_.id INNER JOIN threats t2_ ON a0_.threat_id = t2_.id INNER JOIN vulnerabilities v3_ ON a0_.vulnerability_id = v3_.id LEFT JOIN measures m4_ ON a0_.measure1_id = m4_.id LEFT JOIN measures m5_ ON a0_.measure2_id = m5_.id LEFT JOIN measures m6_ ON a0_.measure3_id = m6_.id WHERE a0_.anr_id = ? AND a0_.status = ?' with params [1, 1]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't2_.a' in 'field list' (500)

It's a bit hard to catch them, since they disappear again quickly.

**Comment by cedricbonhomme** [comment]
It seems that a database upgrade script failed some times ago for your instance.
Could you please check again?

**Comment by sarah-peter** [comment]
It works again. Thank you very much!
