### ISSUE TITLE
Managing models

### ISSUE THREAD

**Issue by keoni161** [monarc-project/MonarcAppFO#146]
Hello everyone,
First of all, I would like to thank you for a truly exceptional product.
Could you please point me in the right direction in relation to managing the models/schemas used?
I could not find any documentation on this.
Thank you
Claudiu

**Comment by cedricbonhomme** [comment]
Hi,
you can use the [back office of MONARC](https://www.monarc.lu/documentation/administrator-guide) for the management of models.
And in case you do not want/want need to install it, you can simply use the knowledge base of your risk analysis.
If you wonder about the difference between the back and front office: https://www.monarc.lu/product/

For the creation/sharing of new models we are actually introducing a new solution, [MOSP](https://github.com/CASES-LU/MOSP).  Some objects available for MONARC are available here:
http://objects.monarc.lu/organization/MONARC
