### ISSUE TITLE
Add referential after risk analysis has been made

### ISSUE THREAD

**Issue by cudeso** [monarc-project/MonarcAppFO#151]
In v2.8.1 when you create a new risk analysis you can add a referential (NIST, ISO, ...).
If you don't select a referential when creating the new analysis you not add it afterwards.

Solution: include in the documentation that you can not add it afterwards or include an option to import it afterwards via the Knowledge Base.

**Comment by cedricbonhomme** [comment]
You should be able to add a referential via the 'Edit risk analysis' button. Don't you see the option ? You can not remove a referential via the screen.

Also it possible to add or remove a referential via the knowledge base.

**Comment by cudeso** [comment]
Indeed, you can add them via 'Edit risk analysis'. Thank you for the swift update, wasn't clear from the referential § in the documentation.
Via knowledge base you can add the 'custom' made but not the pre-made (NIST/ISO).

**Comment by cedricbonhomme** [comment]
Indeed with the next release the knowledge base will be connected to objects.monarc.lu (not only for referentials).
