### ISSUE TITLE
Edit label of added Referentials does not work

### ISSUE THREAD

**Issue by cudeso** [monarc-project/MonarcAppFO#153]
In v. 2.8.1

- Create a new referential in Knowledge Base
- Click pencil (edit referential), change label, click save
- No error messages but label is not changed.
- Also after refresh screen and in risk treatment (Security referentials)

**Comment by cedricbonhomme** [comment]
Also not able to reproduce on my.monarc.lu even without refreshing the web page.
But I just noticed this problem on my dev instance, weird. I will investigate.
