### ISSUE TITLE
Export dashboard as PPTX , template?

### ISSUE THREAD

**Issue by cudeso** [monarc-project/MonarcAppFO#154]
The export of the dashboard to PPTX is a good feature to get a direct overview of all the graphs in the dashboard. 
But where can you define the PPTX template (or logo's) to use that make up this PPTX?

**Comment by cedricbonhomme** [comment]
maybe we can investigate this. Actually template should be a CSS file,  if possible.

**Comment by ruslanbaidan** [comment]
Implemented
