### ISSUE TITLE
Importing vulnerabilities from MOSP doesn't work

### ISSUE THREAD

**Issue by cudeso** [monarc-project/MonarcAppFO#155]
v2.8.1

- https://objects.monarc.lu/object/view/53#
- Export The Whole object and then importing : gives "File error Wrong schema"
- Export Only values in JSON : nothing happens, no error or OK

**Comment by cedricbonhomme** [comment]
This is not supposed to work in version 2.8.1. We introduced import of referentials from MOSP in version 2.8.0.
Import of vulnerabilities (and threats) will land in the next release when the migration of the database with UUIDs for the these objects will be done.
