### ISSUE TITLE
Error when creating 1st risk analysis after installation

### ISSUE THREAD

**Issue by dr-redoute** [monarc-project/MonarcAppFO#163]
After a manual installation of MONARC FO 2.8.2 on Ubuntu 18.04 (either following INSTALL doc or using bootstrap shell) I get the following error when trying to create 1st risk analysis:

An error occurred while fetching api/model-verify-language/31: An exception occurred while executing 'SELECT t0_.uuid AS uuid_0, t0_.label1 AS label1_1, t0_.label2 AS label2_2, t0_.label3 AS label3_3, t0_.label4 AS label4_4, t0_.description1 AS description1_5, t0_.description2 AS description2_6, t0_.description3 AS description3_7, t0_.description4 AS description4_8, t0_.status AS status_9, t0_.mode AS mode_10, t0_.code AS code_11, t0_.trend AS trend_12, t0_.qualification AS qualification_13, t0_.c AS c_14, t0_.i AS i_15, t0_.a AS a_16, t0_.comment AS comment_17, t0_.creator AS creator_18, t0_.created_at AS created_at_19, t0_.updater AS updater_20, t0_.updated_at AS updated_at_21, t0_.anr_id AS anr_id_22, t0_.theme_id AS theme_id_23 FROM threats t0_ WHERE t0_.mode = ?' with params [0]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0_.uuid' in 'field list' (500)

**Comment by cedricbonhomme** [comment]
Could check the content of the table phinx-log in the monarc_cli database and paste it here?
thank you

**Comment by cedricbonhomme** [comment]
Also may in monarc_common database. It may be worth.

**Comment by dr-redoute** [comment]
Cédric,
Here is the content of phinx-log

[monarcFO_issue163_phinx-log_cli.txt](https://github.com/monarc-project/MonarcAppFO/files/3275930/monarcFO_issue163_phinx-log_cli.txt)
[monarcFO_issue163_phinx-log_common.txt](https://github.com/monarc-project/MonarcAppFO/files/3275931/monarcFO_issue163_phinx-log_common.txt)

 table.
Note that when I run ./scripts/update-all.sh
I get this error (but it does not block the update.all script):
```
 == 20190313105800 AddThreatsUuid: migrating
In PdoAdapter.php line 306:
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'uuid'
```

**Comment by cedricbonhomme** [comment]
The `monarc_common` database is missing some migrations:
https://github.com/monarc-project/zm-core/tree/master/migrations/db
(the 5 last migrations).

Since it's the `monarc_common` database, this is not a huge problem. You can drop this database and create it again:
https://github.com/monarc-project/MonarcAppFO/blob/master/vagrant/bootstrap.sh#L253 (line 253 ->256).

Finally you can upgrade it:

`./vendor/robmorgan/phinx/bin/phinx migrate -c ./module/MonarcCore/migrations/phinx.php`

**Comment by dr-redoute** [comment]
Weird... I just checked ./vendor/monarc/frontoffice/migrations/db folder and those 5 lines are here:
```
-rwxrwxr-x 1 monarc monarc   8264 Jun  7 09:30 20190313140400_add_assets_uuid.php*
-rwxrwxr-x 1 monarc monarc   6292 Jun  7 09:30 20190313140500_add_threats_uuid.php*
-rwxrwxr-x 1 monarc monarc  53258 Jun  7 09:30 20190313140600_add_vulnerabilities_uuid.php*
-rwxrwxr-x 1 monarc monarc 404249 Jun  7 09:30 20190325142700_add_amvs_uuid.php*
-rwxrwxr-x 1 monarc monarc  22362 Jun  7 09:30 20190328090400_add_objects_uuid.php*
```
in ./vendor/monarc/core/migrations/db only 4 of them:
```
-rwxrwxr-x 1 monarc monarc    5614 Jun  7 09:30 20190313105800_add_threats_uuid.php*
-rwxrwxr-x 1 monarc monarc   52591 Jun  7 09:30 20190313140600_add_vulnerabilities_uuid.php*
-rwxrwxr-x 1 monarc monarc  402262 Jun  7 09:30 20190325142700_add_amvs_uuid.php*
-rwxrwxr-x 1 monarc monarc   19559 Jun  7 09:30 20190328090400_add_objects_uuid.php*
```

**Comment by dr-redoute** [comment]
Proceeding with monarc_common drop/create/load then upgrade...

**Comment by dr-redoute** [comment]
Still get the error when running phinx migrate.
What about the 5 files that do not have the same timestamps as the ones on git and the fact that one is missing in ./vendor/monarc/core/migrations/db?

**Comment by cedricbonhomme** [comment]
The timestamps (the column `version` of the table phinxlog) seems fine.
If I compare the content of your file `phinx-log_cli.txt` with: https://github.com/monarc-project/zm-client/tree/master/migrations/db
And if I compare the content of your file `phinx-log_common.txt` with: https://github.com/monarc-project/zm-core/tree/master/migrations/db
I do not see a problem. Beside the fact that 5 migrations wew missimg (in your `phinx-log_common.txt`)


Could you paste the output of the command:
`./vendor/robmorgan/phinx/bin/phinx migrate -c ./module/MonarcCore/migrations/phinx.php`
The first time you launched it.

thank you,

**Comment by dr-redoute** [comment]
I saw you latest comment too late. Here is what I did:
I delete monarc folder and started anew (starting from the **git clone** step up to the **sudo npm install -g grunt-cli** step). At this point I ran the update-all.sh and got what you see in update-all.txt
[update-all.txt](https://github.com/monarc-project/MonarcAppFO/files/3276521/update-all.txt)

Having read your comment, I again dropt the DB (both cli & common) and reacreated/populated them and then only ran the phinx-migrate and got this result:
```
Phinx by Rob Morgan - https://phinx.org. 0.5.5

using config file ./vendor/monarc/core/migrations/phinx.php
using config parser php
using migration path /var/lib/monarc/vendor/monarc/core/migrations/db
using seed path /var/lib/monarc/vendor/monarc/core/migrations/seeds
warning no environment specified, defaulting to: common
using adapter mysql
using database monarc01_common

 == 20190312142900 AddAssetsUuid: migrating

In PdoAdapter.php line 306:

  SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'asset_id' doesn't exist in table

migrate [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-t|--target TARGET] [-d|--date DATE]

```

**Comment by cedricbonhomme** [comment]
The script may abruptly stop here:
https://github.com/monarc-project/zm-core/blob/master/migrations/db/20190312142900_add_assets_uuid.php#L94
It's what I can guess from your paste. It's like if asset_id has already been removed in a previous attempt. Which is not possible as you re-created the database.

I just tested on a new database and it worked:

![Screenshot_20190611_151042](https://user-images.githubusercontent.com/465400/59276842-995f2d00-8c4e-11e9-9888-94f715be996d.png)


Is the name 'monarc01_common' OK?

**Comment by dr-redoute** [comment]
Ok I think I have an idea what may cause the issue. As you noted the DB is named monarc01_common. This DB is hosted on a separate dedicated MariaDB server (I use a customized version of the bootstrap.sh allowing for either local DB or remote DB.

The remote DB server is... MariaDB 10.2.11
Local MariaDB server used in all-in-one MonarcFO setup is MariaDB 10.1

Googling the error thrown by the script, I ended on a page explaining that starting with MariaDB 10.2.8, dropping a column that is part of a multi-column UNIQUE constraint is not permitted. (https://mariadb.com/kb/en/library/alter-table/#drop-column). And I add a look at the ./vendor/monarc/core/migrations/db/20190312142900_add_assets_uuid.php and it seems there are some column dropping there...

Trying this work-around for now:
- Install with local DB
- Dump whole lolca DB (common & cli)
- Load DB on remote server
- Reconfigure MonarcFO to point to remote DB

**Comment by dr-redoute** [comment]
Workaround fails...
Will have to wait until MariaDB >10.2.7 is supported for MonarcFO before we can use external MariaDB dedicated master-slave cluster.
Sorry to have bothered you with this.

**Comment by cedricbonhomme** [comment]
OK, thank you for the information. I will close the issue for now. We will soon update the SQL files under the `db-bootstrap` directory to match the current state of the models. So that you won't have to run the upgrade scripts. This will solve your problem.
