### ISSUE TITLE
Drag & drop in risk treatment plan fails after 1 change

### ISSUE THREAD

**Issue by cudeso** [monarc-project/MonarcAppFO#167]
In the risk treatment plan you can only drag & drop one recommendation (change position).
When you try the second recommendation the text isn't draggable.
Version v. 2.8.1
Browser Chrome Version 74.0.3729.169 on OSX

**Comment by jerolomb** [comment]
hello,

it's corrected in 2.8.2 normally.

**Comment by jerolomb** [comment]
in fact the re is an other problem due to an external library, we will fix it
