### ISSUE TITLE
Start risk analysis from existing one gives 500 error

### ISSUE THREAD

**Issue by cudeso** [monarc-project/MonarcAppFO#168]
Starting a new risk analysis from an existing risk analysis gives the error

angular-common-libs.js:113 POST https://monarc.yourict.be/training/api/client-duplicate-anr 500 (Internal Server Error)

{"errors":[{"message":"Call to a member function get() on null","error":"error-exception","exception":{"class":"Error","file":"\/var\/lib\/monarc\/fo\/vendor\/monarc\/frontoffice\/src\/MonarcFO\/Service\/AnrService.php","line":1037,"message":"Call to a member function get() on null","stacktrace":"#0 \/var\/lib\/monarc\/fo\/vendor\/monarc\/frontoffice\/src\/MonarcFO\/Controller\/ApiDuplicateAnrController.php(36): MonarcFO\\Service\\AnrService-\u003EduplicateAnr(Object(MonarcFO\\Model\\Entity\\Anr), \u0027cli\u0027, NULL, Array)\n#1 \/var\/lib\/monarc\/fo\/vendor\/zendframework\/zend-mvc\/src\/Controller\/AbstractRestfulController.php(458): MonarcFO\\Controller\\ApiDuplicateAnrController-\u003Ecreate(Array)\n#2 \/var\/lib\/monarc\/fo\/vendor\/zendframework\/zend-mvc\/src\/Controller\/AbstractRestfulController.php(416): Zend\\Mvc\\Controller\\AbstractRestfulController-\u003EprocessPostData(Object(Zend\\Http\\PhpEnvironment\\Request))\n#3 [internal function]: Zend\\Mvc\\Controller\\AbstractRestfulController-\u003EonDispatch(Object(Zend\\Mvc\\MvcEvent))\n#4 \/var\/lib\/monarc\/fo\/vendor\/zendframework\/zend-eventmanager\/src\/EventManager.php(490): call_user_func(Array, Object(Zend\\Mvc\\MvcEvent))\n#5 \/var\/lib\/monarc\/fo\/vendor\/zendframework\/zend-eventmanager\/src\/EventManager.php(260): Zend\\EventManager\\EventManager-\u003EtriggerListeners(\u0027dispatch\u0027, Object(Zend\\Mvc\\MvcEvent), Object(Closure))\n#6 \/var\/lib\/monarc\/fo\/vendor\/zendframework\/zend-mvc\/src\/Controller\/AbstractController.php(118): Zend\\EventManager\\EventManager-\u003EtriggerEventUntil(Object(Closure), Object(Zend\\Mvc\\MvcEvent))\n#7 \/var\/lib\/monarc\/fo\/vendor\/zendframework\/zend-mvc\/src\/Controller\/AbstractRestfulController.php(300): Zend\\Mvc\\Controller\\AbstractController-\u003Edispatch(Object(Zend\\Http\\PhpEnvironment\\Request), Object(Zend\\Http\\PhpEnvironment\\Response))\n#8 \/var\/lib\/monarc\/fo\/vendor\/zendframework\/zend-mvc\/src\/DispatchListener.php(118): Zend\\Mvc\\Controller\\AbstractRestfulController-\u003Edispatch(Object(Zend\\Http\\PhpEnvironment\\Request), Object(Zend\\Http\\PhpEnvironment\\Response))\n#9 [internal function]: Zend\\Mvc\\DispatchListener-\u003EonDispatch(Object(Zend\\Mvc\\MvcEvent))\n#10 \/var\/lib\/monarc\/fo\/vendor\/zendframework\/zend-eventmanager\/src\/EventManager.php(490): call_user_func(Array, Object(Zend\\Mvc\\MvcEvent))\n#11 \/var\/lib\/monarc\/fo\/vendor\/zendframework\/zend-eventmanager\/src\/EventManager.php(260): Zend\\EventManager\\EventManager-\u003EtriggerListeners(\u0027dispatch\u0027, Object(Zend\\Mvc\\MvcEvent), Object(Closure))\n#12 \/var\/lib\/monarc\/fo\/vendor\/zendframework\/zend-mvc\/src\/Application.php(340): Zend\\EventManager\\EventManager-\u003EtriggerEventUntil(Object(Closure), Object(Zend\\Mvc\\MvcEvent))\n#13 \/var\/lib\/monarc\/fo\/public\/index.php(24): Zend\\Mvc\\Application-\u003Erun()\n#14 {main}"}}]}

Version v. 2.8.2

**Comment by jerolomb** [comment]
for the moment i don't arrive to reproduce. Can you export the origin risk analysis in JSON or a way to reproduce it ?

**Comment by cudeso** [comment]
An export of the analysis is below.
Analysis is in Dutch.
[FED-BE-Demo.json.txt](https://github.com/monarc-project/MonarcAppFO/files/3290590/FED-BE-Demo.json.txt)

**Comment by ruslanbaidan** [comment]
Tested on. MONARC v2.10.2.
Import of the attached file worked well.
@cudeso , the CCB version currently is 2.10.1, but it should work on that version as well.
Could you please validate it.
![Screenshot 2021-03-11 at 15 10 41](https://user-images.githubusercontent.com/3246171/110800406-6e1ecd00-827c-11eb-9642-bf0affac1b6e.png)
