### ISSUE TITLE
Ergonomie

### ISSUE THREAD

**Issue by ThierryPGT** [monarc-project/MonarcAppFO#178]
Hello CASES Team,
Lorsque l'on créé ou l'on duplique un actif de la bibliothèque, avant, le focus était mis sur le nouvel objet et permettait une édition immédiate.
Maintenant, lorsque l'on duplique un actif, le focus reste sur l'actif de départ, donc pour modifier celui que l'on vient de dupliquer, il est nécessaire d'opérer des clics superflus. 
A+
Thierry Petitgenet

**Comment by jfrocha** [comment]
Fixed on some previous release. Works on 2.9.11 release.
