### ISSUE TITLE
Monarc 2.8.3 - nvalid datetime format: 1292

### ISSUE THREAD

**Issue by jkuhr** [monarc-project/MonarcAppFO#179]
when i add a second asset to the riskanalysis, i got the following error: 

Fehler beim Abrufen von api/client-anr/1/instances: An exception occurred while executing 'UPDATE instances SET position = position + 1 WHERE 1 = 1 AND parent_id IS NULL AND anr_id = ? AND position >= ? AND id <> ?' with params [1, 1, ""]: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: '' (500)

any ideas..

**Comment by cedricbonhomme** [comment]
This will be fixed really soon in the next release of MONARC.

**Comment by jkuhr** [comment]
thx for the fast feedback.
