### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by cvannier** [monarc-project/MonarcAppFO#189]
Hi
I've folowed the installation guide for binary but I've an error:
root@monarc-virtual-machine:/var/lib/monarc/fo/db-bootstrap# mysql -u user monarc_common < db-bootstrap/monarc_structure.sql
**bash: db-bootstrap/monarc_structure.sql: Aucun fichier ou dossier de ce type**
root@monarc-virtual-machine:/var/lib/monarc/fo/db-bootstrap# 
If you have an idea to fix it?
Regards

**Comment by cedricbonhomme** [comment]
Hi,

from your prompt I can see that you are already in the `db-bootstrap` folder. But after the prompt you persist specifying the name of the folder `db-bootstrap`. Which is superfluous.

**Comment by eurodude** [comment]
Hi,

I will assume this issue fixed as @cedricbonhomme provided a fix and no more problems were identified afterwards.

Regards
