### ISSUE TITLE
Deliverables template should be stored in a dedicated folder, not in the database

### ISSUE THREAD

**Issue by cedricbonhomme** [monarc-project/MonarcAppFO#19]
I think it would be better to not store template of deliverables on database blob fields.

Storing then on a dedicated folder would ease the customization per analysis.

**Comment by jerolomb** [comment]
done with MonarcAppFO:b8fce0c and zm-client: 4e849e7  

The FO now use the file in /deliveries/cases/LANGUAGE/x.doc with x = 1,2 or 3 following the numbering of the method.

To DO : - Test with an installation  BO/FO 
- clean the code in BO who manage the template and the table in common DB

**Comment by cedricbonhomme** [comment]
should we also have a migration script in order to remove the blob for the templates in the database (at least for the FO for the moment)

**Comment by jerolomb** [comment]
yes it's a part of the second point :)
