### ISSUE TITLE
ejected when get in register GDPR with read rights

### ISSUE THREAD

**Issue by jfrocha** [monarc-project/MonarcAppFO#190]
PUT Request loading page.
https://github.com/monarc-project/ng-anr/blob/2576580314b2d69ffe57fa6bac13600c7f8e2ae8/views/anr.ropa.html#L407

**Comment by cedricbonhomme** [comment]
Actually not able to reproduce this on the feature/upgrade-to-zf3 branch: no PUT request.
But indeed this issue is present in master.

**Comment by cedricbonhomme** [comment]
reproduced after migration to ZF3. I look at it.

**Comment by jfrocha** [comment]
There are still some "add buttons" enabled in read right. Should be hidden.

**Comment by cedricbonhomme** [comment]
I am having a look but I can't find these. Can you explain where?

**Comment by cedricbonhomme** [comment]
Holy shit, even on production I can't find these. Better to see this later...
