### ISSUE TITLE
Upgrade to ZendFramework3 known issues / improvements.

### ISSUE THREAD

**Issue by ruslanbaydan** [monarc-project/MonarcAppFO#193]

**Comment by eurodude** [comment]
Looks to be a duplicate of #15 or at least an extension...

**Comment by jerolomb** [comment]
- [ ]  Snapshotting -> error 500 on the RPI on the anr_id 59

**Comment by cedricbonhomme** [comment]
I managed to upgrade MONARC 2.2.0 (in an old Ubuntu Artful VM with PHP 7.1.11) to future 2.9.1 version, with this script:.

`$ curl -sSL https://raw.githubusercontent.com/monarc-project/website/master/content/assets/scripts/upgrade-to-2.9.1.sh | sudo -u www-data bash`

So it is working with PHP 7.1. Even if this is discouraged (https://www.php.net/supported-versions.php). We can warn users about this in the next blog post for the release.

**Comment by ruslanbaydan** [comment]
Fixed
