### ISSUE TITLE
FO -> Risk sheet -> edit recommendation

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#195]
In case of editing a recommendation (for exemple change the importance) which is link to the risk and the try to save it. It doesn't save : javascript error

angular-common-libs.js:127 TypeError: Cannot read property 'uuid' of null
    at m.CreateRecommandationDialog.$scope.create (RiskRecommendationPartialCtrl.js:260)

**Comment by cedricbonhomme** [comment]
fixed in monarc-project/ng-anr@c84a29321bde14b11e9524d929c8285baca3c76f
