### ISSUE TITLE
Issue when installing Monarc

### ISSUE THREAD

**Issue by gregorygrevin** [monarc-project/MonarcAppFO#197]
Hello,

I am currently installing monarc on a Ubuntu 18.04 LBS server. I followed every steps on your install guide but I have an issue when I am trying to reach localhost:3306 (screenshot 1)
![screenshot1](https://user-images.githubusercontent.com/9590506/68608244-b3799180-04b2-11ea-8ea7-f6c4e0e8f531.PNG)

And I have a blank page when I am trying to connect to localhost:80 (screenshot 2)
![screenshot2](https://user-images.githubusercontent.com/9590506/68608245-b3799180-04b2-11ea-8ea7-b9f1bd6f99df.PNG)
However, I am able to reach some images on /var/lib/monarc/fo/public/img/ (screenshot 3)
![screenshot3](https://user-images.githubusercontent.com/9590506/68608702-d3f61b80-04b3-11ea-9004-15553273dc2a.PNG)

Does someone have a lead on my issue?

**Comment by cedricbonhomme** [comment]
Could you please give us the logs of Apache ?
Generally a blank screen means that there is a problem of database connection/configuration.

**Comment by gregorygrevin** [comment]
You are right, my problem comes from database connection according to logs.
Here is my mistake : when I configured my database, I used this command:
mysql -u root monarc_common < db-bootstrap/monarc_data.sql
It didn't return me access denied but I think it didn't work

Moreover when I tried to simply connect to the database using : mysql --user root
It returns "Access denied for user 'root' @ 'localhost'

The only way to access it is by using : sudo mysql --user root

What should I do now?
Sorry for the inconvenience I am not an expert with databases.

**Comment by cedricbonhomme** [comment]
DROP databases `monarc_cli` and `monarc_common`;
Then re-initializes the databases:
https://github.com/monarc-project/MonarcAppFO/blob/master/vagrant/bootstrap.sh#L282-L287
The variables `$DBUSER_MONARC` and `$DBPASSWORD_MONARC` can be found in `config/autoload/local.php`.

Create the default user (admin@admin.test / admin):
https://github.com/monarc-project/MonarcAppFO/blob/master/vagrant/bootstrap.sh#L306

Upgrade the database:
./scripts/update-all.sh -c

**Comment by gregorygrevin** [comment]
I tried to reinstall from scratch, I wanted to create databases so I tried to connect like this:
test@test:/var/lib/monarc/fo/module/node_modules$ mysql -u root
ERROR 1698 (28000): Access denied for user 'root'@'localhost'

I google the error and tried to fix it by creating another user ("sqlmonarcuser") without password
https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost


test@test:/var/lib/monarc/fo/module/node_modules$ mysql -u sqlmonarcuser
ERROR 1524 (HY000): Plugin 'auth_socket' is not loaded
test@test:/var/lib/monarc/fo/module/node_modules$ sudo mysql -u root
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 37
Server version: 10.1.41-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> select user, host, plugin, password from mysql.user;
+---------------+-----------+-------------+-------------------------------------------+
| user          | host      | plugin      | password                                  |
+---------------+-----------+-------------+-------------------------------------------+
| root          | localhost | unix_socket | *81F5E21E35407D884A6CD4A731AEBFB6AF209E1B |
| sqlmonarcuser | localhost | auth_socket |                                           |
+---------------+-----------+-------------+-------------------------------------------+
2 rows in set (0.00 sec)

The only way to access to the database is to use this command : 
sudo mysql -u root

I created databases and when I tried to initialize them and I still have this error:
test@test:/var/lib/monarc/fo$ sudo mysql -u sqlmonarcuser monarc_common < db-bootstrap/monarc_structure.sql
ERROR 1524 (HY000): Plugin 'auth_socket' is not loaded

Do you have any advice?

**Comment by gregorygrevin** [comment]
Update! I followed this post to correct my ERROR and now everything is working!
https://stackoverflow.com/questions/37879448/mysql-fails-on-mysql-error-1524-hy000-plugin-auth-socket-is-not-loaded

Thank you for your help!
