### ISSUE TITLE
First connection issue

### ISSUE THREAD

**Issue by gregorygrevin** [monarc-project/MonarcAppFO#198]
Hello,

Now that I can reach the web interface, I have another issue : An error occured while fetching api/users-roles: 500 (500).
![screenshot1](https://user-images.githubusercontent.com/9590506/68697958-cace8280-0577-11ea-9d58-664c8569d5a9.png)

I checked other issues on github and these might help you: 
![screenshot2](https://user-images.githubusercontent.com/9590506/68699039-239f1a80-057a-11ea-9802-7d7e3b05086d.png)
![screenshot3](https://user-images.githubusercontent.com/9590506/68699043-2568de00-057a-11ea-8789-ddc53075b536.png)
![screenshot4](https://user-images.githubusercontent.com/9590506/68699046-269a0b00-057a-11ea-9fa8-001bfed06d9a.png)

And when I browsed website:
![screenshot5](https://user-images.githubusercontent.com/9590506/68699070-31ed3680-057a-11ea-8114-a8f7d2009ed6.png)

I checked and I still have space on my disk.
Thank you for your help.

**Comment by cedricbonhomme** [comment]
Could you check the permissions on the directory `data/`.

**Comment by gregorygrevin** [comment]
Directory data/ was on 775, I set it in 777 and it is now working.

Thank you.
