### ISSUE TITLE
[2.9.1 - 2.9.2] Possibility to create infinite loop in the analysis

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#204]
**Environment**: Prod, Formation.

**Steps to reproduce**:
For example, take a "backup management" from the library and drop it into the analysis. 

Now in the library attach a "back office" which contains "backup management". Refresh the page. it creates an infinite loop in the analysis. 

**Expected behaviour**:
When we try to add a composition in the library, and the child element includes a root element inside of its children, an error message has to be displayed.
User should not be able to make the modification when a root element is presented in children list of another one.

_Note_:
It's maybe present before the 2.9.1

**Comment by jerolomb** [comment]
![image](https://user-images.githubusercontent.com/18661517/69621521-8fd05280-103f-11ea-9608-83784007ab54.png)

**Comment by ruslanbaydan** [comment]
@jerolomb , Could you please specify the environment, where we can reproduce the issue.

**Comment by ruslanbaydan** [comment]
https://github.com/monarc-project/zm-core/pull/13

**Comment by ruslanbaydan** [comment]
Fixed and deployed.
