### ISSUE TITLE
Record of processing activities

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#207]
Updated date and created date are not displayed.

Test in RPi and formation

**Comment by ruslanbaydan** [comment]
https://github.com/monarc-project/zm-core/pull/14
https://github.com/monarc-project/zm-client/pull/11

**Comment by cudeso** [comment]
Remains after updating the latest training VM

**Comment by ruslanbaydan** [comment]
> Remains after updating the latest training VM

This fix is not on production yet. We are going to test all the modifications and deploy a release today together with https://github.com/monarc-project/MonarcAppFO/issues/204.
