### ISSUE TITLE
Edit library category

### ISSUE THREAD

**Issue by jfrocha** [monarc-project/MonarcAppFO#209]
Can't edit name of category. Get this error:

file: "/var/www/monarc/fo/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php"
line: 498
message: "Zend\View\Renderer\PhpRenderer::render: Unable to render template "monarc-fo/api-anr-objects-categories/replace-list"; resolver could not resolve to a file"

**Comment by ruslanbaydan** [comment]
PR: https://github.com/monarc-project/ng-anr/pull/7
