### ISSUE TITLE
Add risk owner on risk sheet

### ISSUE THREAD

**Issue by jfrocha** [monarc-project/MonarcAppFO#21]

**Comment by cedricbonhomme** [comment]
Risk owner will be finally added for the assets.

**Comment by n1x0d** [comment]
I second this. Having a risk owner is almost a necessity and ideally even an asset owner too. 

I have stumbled across monarc and I am glad I found it. As I have started using it I have come to appreciate it's flexibility. However, having those additional attributes would make a huge difference. 

Thank you for your consideration!

**Comment by TheWolfH** [comment]
This indeed seems to be a critical missing feature to me considering that having an assigned risk owner for each risk is a strictly mandatory requirement of ISO 27001.
At the moment, users aiming for certification against ISO 27001 are required to main risk ownership out-of-band (e.g., in an Excel export of the risks), which is a major hassle.
