### ISSUE TITLE
Training VM does not show version number

### ISSUE THREAD

**Issue by cudeso** [monarc-project/MonarcAppFO#210]
The training VM for https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.9.1 does not show the correct version in the left menu. It only shows "v."

![MONARC_by_Cases_lu](https://user-images.githubusercontent.com/256028/70086428-add71d80-1612-11ea-8195-47b0d24344a3.jpg)

**Comment by cedricbonhomme** [comment]
yes, this will be fixed in the next VM to be uploaded.
