### ISSUE TITLE
The type hint of parameter "theme" in method "setTheme" is invalid.

### ISSUE THREAD

**Issue by cudeso** [monarc-project/MonarcAppFO#211]
When using the training VM  https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.9.1 I get an error when editing probability for threat in 1st step of MONARC. Browser is latest Chrome on OSX. Values are not saved.

`An error occurred while fetching api/client-anr/1/instances-risks/34: The type hint of parameter "theme" in method "setTheme" in class "Monarc\Core\Model\Entity\ThreatSuperClass" is invalid. (500)`

Reproduce:

1. Create new analysis
2. Add Model Structure/Front Office to analysis
3. Change threat probability value

**Comment by cudeso** [comment]
Most likely linked; when editing vulnerability qualification, this error is returned (and values are not saved):

`An error occurred while fetching api/client-anr/2/instances-risks/94: The type hint of parameter "theme" in method "setTheme" in class "Monarc\Core\Model\Entity\ThreatSuperClass" is invalid. (500)`

**Comment by cedricbonhomme** [comment]
thank you for the report @cudeso . We identfied the issue and will publish a fix. In the meantime some related fixed have already been pushed. You can get these by updating the VM.

**Comment by cedricbonhomme** [comment]
it will be fixed if you [update your VM](https://www.monarc.lu/documentation/technical-guide/#update-a-single-monarc-instance). Or you wait for the next VM.

**Comment by cudeso** [comment]
I updated the VM according to guidelines of the doc but the error remains.

`An error occurred while fetching api/client-anr/4/instances-risks/412: The type hint of parameter "theme" in method "setTheme" in class "Monarc\Core\Model\Entity\ThreatSuperClass" is invalid. (500)`

**Comment by ruslanbaydan** [comment]
The issue is still presented, we are planning to make a release or deploy a hotfix today to fix this issue and some other.
Will let you know during the day.
