### ISSUE TITLE
Bug in Monarc setup on Debian 10 following documentation

### ISSUE THREAD

**Issue by Foxi352** [monarc-project/MonarcAppFO#214]
**Describe the bug**
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'creator' in 'field list'`

**To Reproduce**
Last step of setup, when creating first user:
`php ./vendor/robmorgan/phinx/bin/phinx seed:run -c ./module/Monarc/FrontOffice/migrations/phinx.php`

**Expected behavior**
No error and user created :-)

**Screenshots**
<img width="909" alt="Screenshot 2019-12-08 at 16 17 03" src="https://user-images.githubusercontent.com/5746932/70391495-38829880-19d6-11ea-8d0d-df9f284fcb7c.png">

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Debian 10
| OS version (client)                   | MacOS
| PHP version                             | PHP 7.3.11-1~deb10u1
| MONARC version / git hash     | a674d5e
| Browser                                    | Safari

**Additional context**
Setting up in SSH session as root

**Comment by Foxi352** [comment]
Following advice from #42 worked. Deleting all tables in _cli, rerun `./scripts/update-all.sh -c` and then `php ./vendor/robmorgan/phinx/bin/phinx seed:run -c ./module/Monarc/FrontOffice/migrations/phinx.php` worked. 

But this is still a problem / bug somewhere as i followed your install doc step by step (except that i use nginx instead of apache2).

**Comment by cedricbonhomme** [comment]
Thank you for your report.
I confirm this issue, I already had it but some times ago now. This is a bit weird because the way you solved it, is the expected way (which is described in the documentation and used by the Vagrant deplyment script).
Did you saw an error before the one we can see in your screen shot?

**Comment by Foxi352** [comment]
I don't think so, at least not that i am aware of. I followed the tutorial step by step.
And i can't remember having seen an error before trying to create the initial user.

But i am still not able to login to my new Monarc installation. Tried with admin@admin.localhost and password admin. The answer is that username or password is invalid.

The install is public as it is only a test installation @ https://monarc.wagener.family

**Comment by cedricbonhomme** [comment]
I'll asap re-do an installation on a Debian 10, step by step, following the tutorial.

On your instance there is a HTTP 404 error on api/config. This is maybe a sign of a problem with the configuration (file). And database credentials are in this file.

**Comment by Foxi352** [comment]
Ok, now you got me even more confused. Where does `api/config` come from ? You mean `https://monarc.wagener.family/api/config` ? 

In `/var/lib/monarc/fo/public` i see no folder config, and in your apache config example i see no redirect for /api ? Maybe i got you wrong ...

The only config i am aware of is `/var/lib/monarc/fo/config/autoload/local.php` but this is not in the `fo/public folder` ... I double checked the install doc, and i don't think that i missed a step ...

**Comment by cedricbonhomme** [comment]
I just tried with a brand new VM (Debian 10) and it worked quite well for me.
I made some minor improvements to the install instructions:
https://github.com/monarc-project/MonarcAppFO/commit/103073c1faba4e55e72947c648e8d55f6cb3a238
I do not think that it will solve your issue.
But for me me it worked. I just cut and pasted commands from the install guide.

**Comment by cedricbonhomme** [comment]
> Ok, now you got me even more confused. Where does api/config come from ? You mean https://monarc.wagener.family/api/config ?
Yes, it's an endpoint. I saw an 404 error on it, on your instance.


> In /var/lib/monarc/fo/public i see no folder config, and in your apache config example i see no redirect for /api ? Maybe i got you wrong ...
It is in /var/lib/monarc/fo/ :
https://github.com/monarc-project/MonarcAppFO/blob/master/INSTALL/INSTALL.debian10.md#database-connection
No need to look in public/ . apic/config is just an endpoint of the PHP backend. Not related to a folder you have on your system...

**Comment by cedricbonhomme** [comment]
You should see an output like this :

![Screenshot_20191210_114703](https://user-images.githubusercontent.com/465400/70523243-83b5bc00-1b3a-11ea-990d-60b760e81218.png)

all migrations should pass.


Then at the end:

![Screenshot_20191210_114619](https://user-images.githubusercontent.com/465400/70523270-9203d800-1b3a-11ea-9a15-aa7f3170a0d2.png)

**Comment by cedricbonhomme** [comment]
permissions and configuration file:


![Screenshot_20191210_114946](https://user-images.githubusercontent.com/465400/70523386-da22fa80-1b3a-11ea-81f6-83d62edac8c6.png)

**Comment by Foxi352** [comment]
I retried the update and i have everything exactly like you have.

```root@test:/var/lib/monarc/fo# ./scripts/update-all.sh -c
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 38 (delta 12), reused 20 (delta 6), pack-reused 0
Unpacking objects: 100% (38/38), done.
From https://github.com/monarc-project/MonarcAppFO
   a674d5e..036152a  master     -> origin/master
 * [new tag]         v2.9.2     -> v2.9.2
 * [new tag]         2.9.3      -> 2.9.3
 * [new tag]         v2.9.3     -> v2.9.3
Updating a674d5e..036152a
Fast-forward
 .github/ISSUE_TEMPLATE/bug_report.md      |   5 +-
 .github/ISSUE_TEMPLATE/feature_request.md |   5 +-
 CHANGELOG.md                              |  25 ++++++++++
 INSTALL/INSTALL.debian10.md               |  30 ++++++++----
 VERSION.json                              |   2 +-
 composer.lock                             | 260 +++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------
 package.json                              |   2 +-
 7 files changed, 183 insertions(+), 146 deletions(-)
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 0 installs, 22 updates, 0 removals
  - Updating cakephp/collection (3.8.6 => 3.8.7): Downloading (100%)
  - Updating cakephp/core (3.8.6 => 3.8.7): Downloading (100%)
  - Updating cakephp/utility (3.8.6 => 3.8.7): Downloading (100%)
  - Updating cakephp/log (3.8.6 => 3.8.7): Downloading (100%)
  - Updating cakephp/datasource (3.8.6 => 3.8.7): Downloading (100%)
  - Updating cakephp/cache (3.8.6 => 3.8.7): Downloading (100%)
  - Updating cakephp/database (3.8.6 => 3.8.7): Downloading (100%)
  - Updating doctrine/cache (1.9.1 => 1.10.0): Downloading (100%)
  - Updating zendframework/zend-view (2.11.3 => 2.11.4): Downloading (100%)
  - Updating zendframework/zend-http (2.10.0 => 2.11.1): Downloading (100%)
  - Updating symfony/polyfill-ctype (v1.12.0 => v1.13.1): Downloading (100%)
  - Updating symfony/yaml (v4.4.0 => v4.4.1): Loading from cache
  - Updating symfony/service-contracts (v2.0.0 => v2.0.1): Downloading (100%)
  - Updating symfony/polyfill-php73 (v1.12.0 => v1.13.1): Downloading (100%)
  - Updating symfony/polyfill-mbstring (v1.12.0 => v1.13.1): Downloading (100%)
  - Updating symfony/console (v4.4.0 => v4.4.1): Downloading (100%)
  - Updating symfony/filesystem (v5.0.0 => v5.0.1): Downloading (100%)
  - Updating symfony/config (v4.4.0 => v4.4.1): Downloading (100%)
  - Updating ramsey/uuid (3.8.0 => 3.9.1): Downloading (100%)
  - Updating monarc/core (v2.9.2 => 2.9.3): Downloading (100%)
  - Updating monarc/frontoffice (2.9.2 => 2.9.3): Downloading (100%)
  - Updating roave/security-advisories (dev-master 40fb2c2 => dev-master e4ee2c8)
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Database backup not configured. Skipping.
Phinx by CakePHP - https://phinx.org. 0.11.1

using config file ./vendor/monarc/core/migrations/phinx.php
using config parser php
using migration paths
 - /var/lib/monarc/fo/vendor/monarc/core/migrations/db
using seed paths
warning no environment specified, defaulting to: common
using adapter mysql
using database monarc_common

All Done. Took 0.8154s
Phinx by CakePHP - https://phinx.org. 0.11.1

using config file ./vendor/monarc/frontoffice/migrations/phinx.php
using config parser php
using migration paths
 - /var/lib/monarc/fo/vendor/monarc/frontoffice/migrations/db
using seed paths
 - /var/lib/monarc/fo/vendor/monarc/frontoffice/migrations/seeds
warning no environment specified, defaulting to: cli
using adapter mysql
using database monarc_cli

All Done. Took 0.0228s
+ ng_client@1.0.0
+ ng_anr@1.0.0
added 1 package from 1 contributor, removed 408 packages, updated 5 packages and audited 1898 packages in 19.681s

2 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> canvas@2.6.0 install /var/lib/monarc/fo/node_modules/ng_client/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[canvas] Success: "/var/lib/monarc/fo/node_modules/ng_client/node_modules/canvas/build/Release/canvas.node" is installed via remote

> flag-icon-css@3.4.5 postinstall /var/lib/monarc/fo/node_modules/ng_client/node_modules/flag-icon-css
> opencollective-postinstall || true

Thank you for using flag-icon-css!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/lipis/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
added 409 packages from 309 contributors and audited 734 packages in 21.677s

2 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New patch version of npm available! 6.13.1 → 6.13.3       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.3   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

/var/lib/monarc/fo/node_modules/ng_client /var/lib/monarc/fo
Running "concat:angularCommonLibsJs" (concat) task

Running "concat:angularCommonLibsCss" (concat) task

Done.
/var/lib/monarc/fo
/var/lib/monarc/fo/node_modules/ng_client /var/lib/monarc/fo
Running "nggettext_compile:all" (nggettext_compile) task

Done.
Running "concat:angularCommonLibsJs" (concat) task

Running "concat:angularCommonLibsCss" (concat) task

Done.
935 translated messages.
935 translated messages.
892 translated messages, 40 untranslated messages.

 // Clearing all Metadata cache entries


 [OK] Successfully deleted cache entries.



 // Clearing all Query cache entries


 [OK] Successfully deleted cache entries.



 // Clearing all Result cache entries


 [OK] Successfully deleted cache entries.

```

So i suppose it is related to the fact that i use nginx instead of apache2 as it's the only difference from your setup.

Here is the nginx config i use. Do you have any experience / example config to compare ?
I have no errors in my error.log ...

```
server {
        listen 80;
        listen [::]:80;

        server_name monarc.wagener.family;
        return 301 https://monarc.wagener.family$request_uri;

}

server {
	listen 443;
	listen [::]:443;

	server_name monarc.wagener.family;
	root /var/lib/monarc/fo/public;

	include hhvm.conf;

	ssl on;
	ssl_certificate /etc/letsencrypt/live/monarc.wagener.family/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/monarc.wagener.family/privkey.pem;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
	ssl_prefer_server_ciphers on;
	ssl_session_cache shared:SSL:10m;
	ssl_dhparam /etc/ssl/certs/dhparam.pem;

	access_log /var/www/monarc.wagener.family/logs/access.log;
	error_log /var/www/monarc.wagener.family/logs/error.log;

	client_max_body_size 20M;

	location = /favicon.ico {
		log_not_found off;
		access_log off;
	}

	location = /robots.txt {
		allow all;
		log_not_found off;
		access_log off;
	}

	location ~ /\. {
		deny all;
	}

        location / {
		fastcgi_param APP_ENV production;
                try_files $uri index.php $uri/ =404;
        }

        error_page 404 /404.html;

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
                root /usr/share/nginx/html;
        }

}
```

**Comment by cedricbonhomme** [comment]
I can not really help with Nginx. Your conf file is not working in my VM, with minor changes.


So I tried this:

```
server {
        listen 80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/lib/monarc/fo/public;

        # Add index.php to the list if you are using PHP
        index index.php index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                fastcgi_param APP_ENV production;
                try_files $uri $uri/ =404;
        }

        # pass PHP scripts to FastCGI server
        #
        location ~ \.php$ {
                #include snippets/fastcgi-php.conf;

                # With php-fpm (or other unix sockets):
                #fastcgi_pass unix:/run/php/php7.3-fpm.sock;
                # With php-cgi (or other tcp sockets):
                #fastcgi_pass 127.0.0.1:9000;
                #
                #
                #try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
                #
                #
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}
```

and all I get when I want to load the MONARC login page is a blank page. No errors in Nginx logs.

**Comment by Foxi352** [comment]
As there is no other ongoing test on that server i stopped nginx and launched apache2.
With the proposed config file (simple http) i now get something in my error log.

I think Monarc is not happy with me :-)

`
[Tue Dec 10 14:50:57.638582 2019] [:error] [pid 15153] [client 213.166.55.171:36522] PHP Fatal error:  Uncaught TypeError: Return value of Doctrine\\Common\\Annotations\\AnnotationRegistry::registerLoader() must be an instance of Doctrine\\Common\\Annotations\\void, none returned in /var/lib/monarc/fo/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:117\nStack trace:\n#0 /var/lib/monarc/fo/vendor/doctrine/doctrine-module/src/DoctrineModule/Module.php(40): Doctrine\\Common\\Annotations\\AnnotationRegistry::registerLoader(Object(Closure))\n#1 /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/Listener/InitTrigger.php(31): DoctrineModule\\Module->init(Object(Zend\\ModuleManager\\ModuleManager))\n#2 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\\ModuleManager\\Listener\\InitTrigger->__invoke(Object(Zend\\ModuleManager\\ModuleEvent))\n#3 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\\EventManager\\EventManager->triggerListeners(Object(Zend\\ModuleManager\\ModuleEvent))\n#4 /var/lib/monarc/fo/vendor/zendframewo in /var/lib/monarc/fo/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 117
`

Config is as stated in the docs:

`PHP 7.3.11-1~deb10u1`
`Apache/2.4.38 (Debian)`


```
	<VirtualHost _default_:80>
		ServerAdmin webmaster@localhost
		ServerName monarc.wagener.family

		DocumentRoot /var/lib/monarc/fo/public

		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined

		<Directory /var/lib/monarc/fo/public>
        		DirectoryIndex index.php
        		AllowOverride All
        		Require all granted
    		</Directory>

    		<IfModule mod_headers.c>
       			Header always set X-Content-Type-Options nosniff
       			Header always set X-XSS-Protection "1; mode=block"
       			Header always set X-Robots-Tag none
       			Header always set X-Frame-Options SAMEORIGIN
    		</IfModule>

		SetEnv APP_ENV "production"

	</VirtualHost>
```

**Comment by Foxi352** [comment]
I created a new clean AWS Ubuntu 18.04 Instance with Apache2 following your Ubuntu 18.04 tutorial and that worked !

I only added the `mkdir -p monarc/Monarc`and the chown / chmod commands you modified in your Debian install instructions.

Sor for my testings it's working for me now. Thanks for your help.

**Comment by cedricbonhomme** [comment]
OK, nice to read that. I close this ticket for now.
