### ISSUE TITLE
An asset library is disappeared after creation a category for an asset

### ISSUE THREAD

**Issue by ruslanbaydan** [monarc-project/MonarcAppFO#216]
**Describe the bug**

Specific Assets Library item is disappeared after creation of a new category for an asset under it. 

**To Reproduce**

- Create a new analyse based on Cases Model.
- Go to the Assets Library and open Edit (any) Asset under any category.
- Create a new Category for it *under root* and save the asset.
- The entire library will disappear and the asset will be displayed under the newly created category.

**Expected behaviour**

The library item should not disappear, just the modified asset should be moved outside of it under the new Category.

**App version**
Current ver - 2.9.4.
The same issue was presented in the ver 2.9.0.

**Comment by ruslanbaydan** [comment]
![Screenshot 2019-12-11 at 16 22 39](https://user-images.githubusercontent.com/3246171/70634440-8562ab00-1c32-11ea-8776-7683956d884f.png)

**Comment by ruslanbaydan** [comment]
Related to: https://github.com/monarc-project/MonarcAppFO/issues/209

**Comment by jerolomb** [comment]
related to #205

**Comment by ruslanbaydan** [comment]
https://github.com/monarc-project/ng-anr/pull/8
https://github.com/monarc-project/zm-core/pull/15
https://github.com/monarc-project/zm-client/pull/14

**Comment by ruslanbaydan** [comment]
Fixed on frontoffice and backoffice sides.
