### ISSUE TITLE
New installation PHP Fatal Error zendframework 

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#217]
**Describe the bug**

run "./scripts/update-all.sh -c" as described in the installation instructions. The commas generates the following error

[...]
PHP Fatal error:  Uncaught Zend\ModuleManager\Exception\RuntimeException: Module (Monarc\Core) could not be initialized. in /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php:201
Stack trace:
#0 /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(173): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent))
#1 /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(95): Zend\ModuleManager\ModuleManager->loadModule('Monarc\\Core')
#2 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent))
#3 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent))
#4 /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(118): Zend\EventManager\EventManager->triggerEvent(O in /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 201
PHP Fatal error:  Uncaught Zend\ModuleManager\Exception\RuntimeException: Module (Monarc\Core) could not be initialized. in /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php:201
Stack trace:
#0 /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(173): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent))
#1 /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(95): Zend\ModuleManager\ModuleManager->loadModule('Monarc\\Core')
#2 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent))
#3 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent))
#4 /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(118): Zend\EventManager\EventManager->triggerEvent(O in /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 201
PHP Fatal error:  Uncaught Zend\ModuleManager\Exception\RuntimeException: Module (Monarc\Core) could not be initialized. in /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php:201
Stack trace:
#0 /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(173): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent))
#1 /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(95): Zend\ModuleManager\ModuleManager->loadModule('Monarc\\Core')
#2 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent))
#3 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent))
#4 /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(118): Zend\EventManager\EventManager->triggerEvent(O in /var/lib/monarc/fo/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 201

**To Reproduce**
1. Install a complete new monarc setup on ubuntu 18.04 or Debian 10
2. Follow instructions as described
3. run "./scripts/update-all.sh -c"

**Expected behavior**
Complete the update process without any error.

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Debian or Ubuntu
| OS version (client)                   | MacOS
| PHP version                             | 7.3
| MONARC version / git hash     | 2.9.4
| Browser                                    | Safari

**Comment by cedricbonhomme** [comment]
Hello,

Did you ave created the folder:
module/Monarc
before creating the symlinks.

https://github.com/monarc-project/MonarcAppFO/blob/master/INSTALL/INSTALL.debian10.md#back-end

**Comment by KonzeptAcht** [comment]
Hello, Cederic,

sorry, missed the point 🙈. Can you please add the folder creation "mkdir -p module/Monarc" to the Ubuntu 18.04 installation instructions?

**Comment by cedricbonhomme** [comment]
No worry, it's updated.
