### ISSUE TITLE
Library -> asset -> Asset used in the risks analysis

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#218]
**Describe the bug**
The information is not displayed in the right order
ANR : 
![image](https://user-images.githubusercontent.com/18661517/70696417-f1412400-1cc3-11ea-8632-fa301ff5faf2.png)

Active parents when backup management is selected in the ANR : 
![image](https://user-images.githubusercontent.com/18661517/70696436-fdc57c80-1cc3-11ea-8e1d-ec761a8dd10e.png)

The order must be : test 2.9.4 > business database > building > Backup Management

**To Reproduce**
1. Create an ANR
2. Drop to the ANR from library some assets
3. Click on an asset in the library

**Expected behavior**
Right order (see above)

**Screenshots**
See above

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| Environement             | Formation
| OS version (client)                   | Win10
| MONARC version / git hash     | 2.9.4
| Browser                                    | all

**Additional context**
Not urgent :D

**Comment by ruslanbaidan** [comment]
Released to production ver. 2.9.8.
