### ISSUE TITLE
Error in exporting migration from 2.9.0 to 2.9.4

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#219]
**Describe the bug**
We are not able to export our existing risk analysis including the knowledgebase from our MONARC 2.9.0 (operated on CentOS) to a MONARC 2.9.4 (operated on UBUNTU). We do not use the CASES Knowledgebase, but completely self-created assets.
During an import, the entire knowledgebase remains empty.
 
**To Reproduce**
1. 2.9.0: Go to our own'Risk analysis'
2. 2.9.0: Click on 'Export options „all“'
3. 2.9.4 Create new risk analysis
4. See missing knowledgebase asstes from our exported risk analysis
 
**Expected behavior**
We expected to export and re-import the whole existing risk analysis without any missing content.
 
**Screenshots**
n.a.
 
**Desktop (please complete the following information):**
 
| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.0.4
| OS version (client)                   | MacOS
| PHP version                             | 7.2
| MONARC version / git hash     | 2.9.0 / 2.9.4
| Browser                                    | Safari
 
**Additional context**
Would you be so kind as to give us a hint on how we can correctly export and import or alternatively do you have the possibility to do an analysis with us on our instance?
We need the help also for an upcoming certification according to ISO 27001.

**Comment by cedricbonhomme** [comment]
thank for the report. We are checking this issue.

Export and import from 2.9.4 to 2.9.4 seems to be OK. I'll try from 2.9.0.
There are no database migrations that could impact this since 2.9.0.

**Comment by ruslanbaydan** [comment]
Hello @KonzeptAcht,

We fixed some issues since the version 2.9.4.
Could you please update your Monarc instance to the latest version 2.9.7 and try to perform the described steps again.
In case if the issue has been remained we can investigate it more deeply.

We look forward for the results.

**Comment by ruslanbaidan** [comment]
Regarding your questions:

> alternatively do you have the possibility to do an analysis with us on our instance?

Our aim is to provide support, trainings and help with understanding the Risk Analyses tool such as Monarc, but we don't provide the analysis preparation service.
You can subscribe for the next free training on 28 of April 2020 in our Office space.
The date of the training will be published soon here: https://www.monarc.lu/trainings/
The special trainings requests are not free.
You can also have a look at the other possible trainings: https://cases.lu/services/trainings.html

> We need the help also for an upcoming certification according to ISO 27001.

We don't do that, but there are other companies which can help you with that.

**Comment by KonzeptAcht** [comment]
We created a new Report with new informations under #251
