### ISSUE TITLE
Library categories management issues

### ISSUE THREAD

**Issue by ruslanbaidan** [monarc-project/MonarcAppFO#221]
**The issues description**

The issues are applicable for BackOffice and FrontOffice parts.

1.  Root categories ordering issue.
When we create a root category there is a property to specify the position of the element (in the beginning, in the end or after an element), but new Categories are always created in the beginning. When we edit the category position, it doesn't have any impact, category position stayed the same.

2. Disappeared library sub categories including their assets.
When we create 2 root categories and one of them already has (or we create) child categories with different assets, and then try to set the other root category as child of the first root one in the beginning of the list, the subcategories of the root one are disappeared.
Sometimes the scenarios could be different and not all the categories are not displayed, but 1 or 2 only.

**To Reproduce**

Steps to reproduce the issue #1:
1. Create a new analyse based on Cases Model, if you don't have a test one.
2. Chose an asset from the lib, create and set a new root category for it, category position can be in the end or after another category, save the asset.
3. Do the same for another element.
4. The categories will be in the top and the second created will be the first one.
5. Try to modify one of the root categories position. It doesn't affect its position.

Steps to reproduce the issue #2:
1. Create a new analyse based on Cases Model, if you don't have a test one.
2. Choose an asset from the lib, open the edit UI and create a new root category, save the asset.
3. Do the same for another element.
4. Choose another asset and create a new sub category for it, which is child of the first root one, save the asset.
5. Do the same  for another element. As the result, the first root category should have a 2 or more sub directories.
6. Edit the asset which is under the second root category, edit its category and set the parent one the first root. (position suppose to be in the end).
7. After saving the asset all the other categories under the first root one are disappeared.

**Expected behaviour**

The issue #1: Category should be placed on the specified position.

The issue #2: Display all the categories after the described operations.

**Additional context**
Different library categories management issues were fixed within the following task:
https://github.com/monarc-project/MonarcAppFO/issues/216
There are some related parts of the code still require modifications.

**Comment by ruslanbaydan** [comment]
![Screenshot 2019-12-19 at 17 06 07](https://user-images.githubusercontent.com/3246171/71189919-e5390180-2283-11ea-98b1-615c825fb5fc.png)
![Screenshot 2019-12-19 at 17 07 30](https://user-images.githubusercontent.com/3246171/71189920-e5390180-2283-11ea-8d73-89eacf8344d7.png)
![Screenshot 2019-12-19 at 17 07 59](https://user-images.githubusercontent.com/3246171/71189922-e5390180-2283-11ea-96e9-dc89d44821fd.png)
![Screenshot 2019-12-19 at 17 16 17](https://user-images.githubusercontent.com/3246171/71189923-e5d19800-2283-11ea-8c6d-331c670fc54a.png)
![Screenshot 2019-12-19 at 17 16 37](https://user-images.githubusercontent.com/3246171/71189924-e5d19800-2283-11ea-98c9-47c62b64a4d1.png)

**Comment by ruslanbaidan** [comment]
Fixes for the categories management and https://github.com/monarc-project/MonarcAppFO/issues/229:
https://github.com/monarc-project/zm-core/pull/22/files
https://github.com/monarc-project/zm-client/pull/17/files

In order to fix objects positioning, we need to extract from AbstractEntity its calculation and implement in a separate service. Will be done in separate PRs.

**Comment by ruslanbaidan** [comment]
Released to production ver. 2.9.8.
