### ISSUE TITLE
Global object-> changes comment 

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#224]
**Describe the bug**
In a global object, you modify the value "existing control" it changes the value for all the risks of the asset. 

Precondition : database is corrupted, all the risks in instances_risks table have the same amv_id

**To Reproduce**
1. Have a corrupted database
2. instantiate two times the object 
3. change one value "existing control"

**Expected behavior**
Change only the value to the expected instance_risks and its brothers. 

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 16.04
| OS version (client)                   | not relevant 
| PHP version                             | not relevant 
| MONARC version / git hash     | 2.9.5, 
| Browser                                    | Firefox, Chrome,

**Comment by jerolomb** [comment]
I ve just changed a condition to not only check on the amv_id. We also need to make a phinx script to correct the corrupted database

**Comment by ruslanbaydan** [comment]
We can fix the database consistency if it is required manually by cooperation with the customer(s) who has the problem. We can also keep it like this as far the performed fix will prevent having the issue in the future.
