### ISSUE TITLE
Upload a new template delivery

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#227]
**Describe the bug**
Impossible to upload a new model of template. 

**To Reproduce**
1. Go to the admin parameters 
2. Click on "deliverable templates"
3. Click on plus to add one, upload the template and click create

**Expected behavior**
No error and template uploaded and working 

**Screenshots**

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 |  Ubuntu, ...
| OS version (client)                   |  Win10
| PHP version                             | 7.0, 7.1...
| MONARC version / git hash     | 2.9.5, 
| Browser                                    | Firefox

**Additional context**
message: An exception occurred while executing 'SELECT t0.id AS id_1, t0.category AS category_2, t0.description1 AS description1_3, t0.description2 AS description2_4, t0.description3 AS description3_5, t0.description4 AS description4_6, t0.path1 AS path1_7, t0.path2 AS path2_8, t0.path3 AS path3_9, t0.path4 AS path4_10, t0.editable AS editable_11, t0.creator AS creator_12, t0.created_at AS created_at_13, t0.updater AS updater_14, t0.updated_at AS updated_at_15, t0.anr_id AS anr_id_16 FROM deliveries_models t0 WHERE t0.category = ?' with params [1]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'monarc_common.deliveries_models' doesn't exist

On cloud

**Comment by ruslanbaydan** [comment]
Fixed and released.
