### ISSUE TITLE
Randomly deletion of recommendations 

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#228]
**Describe the bug**
Detach an asset of the anr delete all or a part of all the recommendations. 

**To Reproduce**
1. Create a risk analysis like this 
![image](https://user-images.githubusercontent.com/18661517/71406811-897ec780-2639-11ea-86c6-bd1a93c735f1.png)

2. Create and attach a recommendation to an asset witch has something common (vulnerability, threat etc.) with the other one
![image](https://user-images.githubusercontent.com/18661517/71407018-25a8ce80-263a-11ea-81f4-8e175f00e4d8.png)

3. Detach the assets which are not linked to the recommendations 
4. The recommendations are also deleted 

**Expected behavior**
The recommendation mustn't be deleted

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 |  Ubuntu, ...
| OS version (client)                   | Win10
| PHP version                             | 7.2
| MONARC version / git hash     | 2.9.5, 
| Browser                                    | Firefox

**Additional context**
Tested on production and local machine 
The scenario is maybe not the only one. But it helps to reproduce the bug.

**Comment by ruslanbaydan** [comment]
There are 2 PRs to fix the issue:
https://github.com/monarc-project/zm-client/pull/16
https://github.com/monarc-project/zm-core/pull/20
Might be we need to reorder recommendations after an object removal, needs to be clarified with @jerolomb .

**Comment by ruslanbaydan** [comment]
Deployed on formation:
https://formation.monarc.lu

**Comment by ruslanbaydan** [comment]
Deployed on prod
