### ISSUE TITLE
Library -> global asset -> delete asset

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#229]
**Describe the bug**
Before deleting an object, all the instances (in the environment) of the object are listed

**To Reproduce**
1. Go to your favorite environment 
2. Create several risk analysis like this containing the same assets, for example import several time myprint in several risks analysis (maybe work with snapshots) 
3. Delete an asset from the library
4. You have a pop up message which prevent you to delete and lists the instances of all the analysis

**Expected behavior**
Don't list in the others ANR

**Screenshots**
![image](https://user-images.githubusercontent.com/18661517/71900180-9208ef00-315d-11ea-969f-63fcc8097d9b.png)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 |  Ubuntu
| OS version (client)                   | , Win10, , ...
| PHP version                             | 7.1...
| MONARC version / git hash     | 2.9.7 
| Browser                                    | Firefox,

**Comment by ruslanbaidan** [comment]
Released to production ver. 2.9.8.
