### ISSUE TITLE
Duplication of risks in Deliverable -> appendix D

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#233]
**Describe the bug**
In the appendix D all the risks (in all the branches of the tree of the ANR) appear and sometimes it takes more than that. 

**To Reproduce**
Take a risk analysis like this for exemple with at least one global object instantiate 2 times. 
![image](https://user-images.githubusercontent.com/18661517/72258365-2bc51600-360e-11ea-99e4-1b2ee392b35c.png)

With 3 instantiations of Building i have 20 risks in my report instead of 5 
![image](https://user-images.githubusercontent.com/18661517/72258598-c3c2ff80-360e-11ea-8f13-b844c3f963ac.png)

**Expected behavior**
Global object must appear just one time with the highest risk in the appendix D. In the case of building just 5 risks

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 |  Ubuntu, 
| OS version (client)                   |  Win10, 
| PHP version                             | 7.2
| MONARC version / git hash     | 2.9.8 and probably before
| Browser                                    |  Chrome

**Additional context**
Test on formation

**Comment by ruslanbaidan** [comment]
PR with the fix and some code styles fixes:
https://github.com/monarc-project/zm-client/pull/20/files
The fix itself is just here:
https://github.com/monarc-project/zm-client/pull/20/files#diff-5458dbe8b10959c55f1ce1200f9201adR1244-R1257
