### ISSUE TITLE
Cascade delete of instances_risks

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#242]
**Describe the bug**
When you delete some risks in the KB, there are not propagated to the instances_risks table so the anr. It results to an inconsistent DB

**To Reproduce**
1. Go to your favorite analysis, take a snapshot and select one asset, for exemple this one in my case which has the type OV_UTIL : 
![image](https://user-images.githubusercontent.com/18661517/73068216-f4c2f000-3eaa-11ea-921e-83ba8ee3986d.png)

2. Go to the Knowledge Base and delete all the risks of OV_UTIL to have this result (no more information risk on ov_util):
![image](https://user-images.githubusercontent.com/18661517/73068275-28057f00-3eab-11ea-847c-31b1ab0355c0.png)
 
3. Scroll down to your library and check, no more risks it's ok 
![image](https://user-images.githubusercontent.com/18661517/73068355-4c615b80-3eab-11ea-95b5-300303c83d8f.png)

Go to the same assets in the ANR : 
![image](https://user-images.githubusercontent.com/18661517/73068216-f4c2f000-3eaa-11ea-921e-83ba8ee3986d.png)

4. The risks are still there !!! 

**Expected behavior**
The instances_risk in the anr has to be switch to specific=1, so in the ANR the risks become blue and can be manually deleted and it prevents the accidental lose of information. 

NB : can be usefull or not to set the amv_id to NULL

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu, ...
| OS version (client)                   | Win10, 
| PHP version                             | ?
| MONARC version / git hash     | 2.9.9, 
| Browser                                    | Firefox, Chrome

**Additional context**
Test on several environment on 2.9.9

**Comment by ruslanbaidan** [comment]
Was fixed
