### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#243]
**Describe the bug**
In some case there is an error when trying to import from 2.9.9 to 2.9.9 

**To Reproduce**
1. Go to your favorite analysis which contains information risks no needs to be huge : 
![image](https://user-images.githubusercontent.com/18661517/73072178-deba2d00-3eb4-11ea-9fd2-b450e915ff3d.png)

2. Make an export of the whole analysis with or without assessment
3. Import it in a new analysis

**Expected behavior**
Proper import without error 

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Debian, Ubuntu, ...
| OS version (client)                   |  Win10
| PHP version                             | ?
| MONARC version / git hash     | 2.9.9, 
| Browser                                    | Firefox

**Additional context**
Tested on several environment
Possibly unhandled rejection: {"data":{"errors":[{"message":"Label is required","error":"error-exception","exception":{"class":"Monarc\\Core\\Exception\\Exception","file":"/var/lib/monarc/fo/vendor/monarc/core/src/Model/Entity/AbstractEntity.php","line":197,"message":"Label is required","stacktrace":"#0 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Service/AnrAssetService.php(183): Monarc\\Core\\Model\\Entity\\AbstractEntity->exchangeArray(Array)\n#1 /var/lib/monarc/fo/vendor/monarc/core/src/Service/ObjectExportService.php(183): Monarc\\FrontOffice\\Service\\AnrAssetService->importFromArray('2.9.9', Array, Object(DoctrineORMModule\\Proxy\\__CG__\\Monarc\\FrontOffice\\Model\\Entity\\Anr), Array)\n#2 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Service/AnrInstanceService.php(173): Monarc\\Core\\Service\\ObjectExportService->importFromArray(Array, Object(DoctrineORMModule\\Proxy\\__CG__\\Monarc\\FrontOffice\\Model\\Entity\\Anr), 'merge', Array)\n#3 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Service/AnrInstanceService.php(1055): Monarc\\FrontOffice\\Service\\AnrInstanceService->importFromArray(Array, Object(DoctrineORMModule\\Proxy\\__CG__\\Monarc\\FrontOffice\\Model\\Entity\\Anr), 5687, 'merge', false, Array)\n#4 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Service/AnrInstanceService.php(1055): Monarc\\FrontOffice\\Service\\AnrInstanceService->importFromArray(Array, Object(DoctrineORMModule\\Proxy\\__CG__\\Monarc\\FrontOffice\\Model\\Entity\\Anr), 5686, 'merge', false, Array)\n#5 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Service/AnrInstanceService.php(1579): Monarc\\FrontOffice\\Service\\AnrInstanceService->importFromArray(Array, Object(DoctrineORMModule\\Proxy\\__CG__\\Monarc\\FrontOffice\\Model\\Entity\\Anr), NULL, 'merge', false, Array, true)\n#6 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Service/AnrInstanceService.php(88): Monarc\\FrontOffice\\Service\\AnrInstanceService->importFromArray(Array, Object(DoctrineORMModule\\Proxy\\__CG__\\Monarc\\FrontOffice\\Model\\Entity\\Anr), NULL, 'merge', false, Array, true)\n#7 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Controller/ApiAnrImportAbstractController.php(39): Monarc\\FrontOffice\\Service\\AnrInstanceService->importFromFile(227, Array)\n#8 /var/lib/monarc/fo/vendor/zendframework/zend-mvc/src/Controller/AbstractRestfulController.php(471): Monarc\\FrontOffice\\Controller\\ApiAnrImportAbstractController->create(Array)\n#9 /var/lib/monarc/fo/vendor/zendframework/zend-mvc/src/Controller/AbstractRestfulController.php(429): Zend\\Mvc\\Controller\\AbstractRestfulController->processPostData(Object(Zend\\Http\\PhpEnvironment\\Request))\n#10 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\\Mvc\\Controller\\AbstractRestfulController->onDispatch(Object(Zend\\Mvc\\MvcEvent))\n#11 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\\EventManager\\EventManager->triggerListeners(Object(Zend\\Mvc\\MvcEvent), Object(Closure))\n#12 /var/lib/monarc/fo/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\\EventManager\\EventManager->triggerEventUntil(Object(Closure), Object(Zend\\Mvc\\MvcEvent))\n#13 /var/lib/monarc/fo/vendor/zendframework/zend-mvc/src/Controller/AbstractRestfulController.php(313): Zend\\Mvc\\Controller\\AbstractController->dispatch(Object(Zend\\Http\\PhpEnvironment\\Request), Object(Zend\\Http\\PhpEnvironment\\Response))\n#14 /var/lib/monarc/fo/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\\Mvc\\Controller\\AbstractRestfulController->dispatch(Object(Zend\\Http\\PhpEnvironment\\Request), Object(Zend\\Http\\PhpEnvironment\\Response))\n#15 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\\Mvc\\DispatchListener->onDispatch(Object(Zend\\Mvc\\MvcEvent))\n#16 /var/lib/monarc/fo/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\\EventManager\\EventManager->triggerListeners(Object(Zend\\Mvc\\MvcEvent), Object(Closure))\n#17 /var/lib/monarc/fo/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\\EventManager\\EventManager->triggerEventUntil(Object(Closure), Object(Zend\\Mvc\\MvcEvent))\n#18 /var/lib/monarc/fo/public/index.php(34): Zend\\Mvc\\Application->run()\n#19 {main}"}}]},"status":412,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/client-anr/227/instances/import","data":{"mode":"merge","file":[{}],"password":""},"_isDigested":true,"_chunkSize":null,"headers":{"Accept":"application/json, text/plain, */*","token":"mysecrettoken"},"_deferred":{"promise":{}},"cached":false},"statusText":"Precondition Failed","xhrStatus":"complete"}

[testexport(2).json.txt](https://github.com/monarc-project/MonarcAppFO/files/4108638/testexport.2.json.txt)

**Comment by cedricbonhomme** [comment]
https://github.com/monarc-project/zm-core/pull/26

**Comment by ruslanbaidan** [comment]
- https://github.com/monarc-project/zm-core/pull/27
- https://github.com/monarc-project/zm-client/pull/26
