### ISSUE TITLE
Risks and measures 

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#244]
**Describe the bug**
Take an existing analysis. Create a custom referential or use the existing one. 
Link in the knowledge base a measure to a risk. The measure is well linked in the DB but doesn't appear 

**To Reproduce**
1. Take an existing analysis. 
2. Create a custom referential or use the existing one. 
3. Link in the knowledge base a measure to a risk. The measure is well linked in the DB but doesn't appear in the risk sheet like the others 

In my case i ve created a new referential "mon ref" and a new measure "dede", linked with a risks : 
![image](https://user-images.githubusercontent.com/18661517/73265354-1981d500-41d5-11ea-8704-cdfb8d22a284.png)

Take the concerned risk in the anr (ov_backup, MA16, 1174)

![image](https://user-images.githubusercontent.com/18661517/73265745-d4aa6e00-41d5-11ea-89af-ee0d0dbec1d7.png)

The measure is not present. Take now the SOA view : 

![image](https://user-images.githubusercontent.com/18661517/73265847-04f20c80-41d6-11ea-9976-bc68ca74de5e.png)

The measure is not present (code is not clickable)

**Expected behavior**
See all the measure related to the risks, in the risk view and in the SOA view

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 |  Ubuntu.
| OS version (client)                   |  Win10, 
| PHP version                             | 7.0, 7.1...
| MONARC version / git hash     | 2.9.9, 
| Browser                                    | Chrome

**Additional context**
Tested on local machine and cloud environment

**Comment by ruslanbaidan** [comment]
Works fine now.
