### ISSUE TITLE
Run monarc under a context path (e.g: /monarc/)

### ISSUE THREAD

**Issue by eLvErDe** [monarc-project/MonarcAppFO#250]
Hello,

It could be useful to be able to run Monarc behind a context_path, e.g: if Monarc is exposed using a reverse proxy, it's a lot more convenient to have the whole app leaving under /monarc/.

Best regards, Adam.

**Comment by cedricbonhomme** [comment]
We are using `context_path` with a reverse proxy on our production server. Maybe I can help you by explaining how we did it with for example the context _context_.

On a MONARC font office server in the file /etc/apache2/sites-enabled/context.conf we have:

```
...
SetEnv "APP_CONF_DIR" /var/www/context/
SetEnv "APP_DIR" /var/lib/monarc/fo
...
```
APP_DIR can have another value.

and in the file /var/www/context/local.php (the configuration file of MONARC...), we have:

```
....
    'publicHost' => 'https://my.monarc.lu/context',
);

```

Then, for the reverse proxy (an other server), we have the file /etc/apache2/sites-enabled/my.monarc.lu.conf which contains:

`        Include "/etc/apache2/client_redirection"`

And this file contain the `ProxyPass` and `ProxyPassReverse` clauses.

**Comment by eLvErDe** [comment]
Hi Cedric,

Thanks for your anwser. I'm trying to figure out how to adapt this to my setup but I think there's a missing part.
I just added (at root level) "publicHost" in /var/lib/monarc/fo/config/autoload/local.php but I can see the angular frontend still doing calls on /.
I'm pretty sure I have to rebuilt the angular frontend somehow to make it relative to the context_path.

Regards, Adam.

**Comment by cedricbonhomme** [comment]
I check if we have set up something more, but I doubt.
You do not have to recompile the JavaScript part. We are using several contexts with the same code.

**Comment by cedricbonhomme** [comment]
I do not think I forgot something. It's all from our Ansible playbook.
Concerning the reverse proxy:
https://github.com/monarc-project/ansible-ubuntu/blob/master/playbook/monarcrpx/templates/clients_redirection.j2
https://github.com/monarc-project/ansible-ubuntu/blob/master/playbook/monarcrpx/templates/reverse_proxy_apache.conf.j2

For MONARC:
https://github.com/monarc-project/ansible-ubuntu/blob/master/playbook/monarcfo/templates/client_config.php.j2
https://github.com/monarc-project/ansible-ubuntu/blob/master/playbook/monarcfo/templates/client_apache.conf.j2

**Comment by cedricbonhomme** [comment]
Hey,
do you still have issues with this?
