### ISSUE TITLE
500 Error Creating Snapshot or generating deliverable

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#251]
**Describe the bug**
In reference to the open ticket Cases#9579 and #219 there is still the problem of generating reports or snapshots if the Cases.lu model is not used for risk analysis. In this case a 500 error is displayed.
We have found out that it seems to have to do with the links under "Information Risks", because only after successful linking the mentioned error occurs. 
The error is also adjustable in the risk analysis of KonzeptAcht GmbH hosted at monarc.lu.

**To Reproduce**

1. Using non Cases Model Like Described in Cases#9579 or the monarc.lu hosted Risk Management
2. creating links under "Information Risks" in the Knowledgebase
3. Create a Snapshot or generating a Report
4. See Error

**Expected behavior**
Ability to generate snapshots and reports without error messages

**Screenshots**
![alt text](https://www.konzeptacht.de/wp-content/uploads/2020/02/Monarc-Error-500.png)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04 LTS
| OS version (client)                   | MacOS, Win10, Win7, Debian
| PHP version                             | 7.3
| MONARC version / git hash     | 2.9.9
| Browser                                    | Firefox, Safari

**Additional context**

Error Report Web Conole:

[Error] Possibly unhandled rejection: {"data":"","status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","data":{"anr":2,"comment":"Test"},"url":"api/client-anr/2/snapshot","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","token":"93de3bbfda57eeaf14ab3a9b066cb4b047badd1562a3e5538d07ffb6df3e665d405da15e43d99a19e509.76687333"},"cached":false},"statusText":"Internal Server Error","xhrStatus":"complete","resource":{"anr":2,"comment":"Test"}}
	(anonyme Funktion) (angular-common-libs.js:99)
	g (angular-common-libs.js:139:239)
	$digest (angular-common-libs.js:151:187)
	$apply (angular-common-libs.js:155)
	k (angular-common-libs.js:106:136)
	v (angular-common-libs.js:111:208)
	(anonyme Funktion) (angular-common-libs.js:112:127)

**Comment by ruslanbaidan** [comment]
Hello,

We can't reproduce the issues on our production instances.

Could you please try to update your version to 2.9.10. (Our current production version is 2.9.10, but version also did not have the issue 2.9.9).

To have more context information about the reason of the error you have we need to see your /var/apache2/error.log (you can send it to info@cases.lu). Depends on your apache configuration it can be placed in different directory (ErrorLog parameter in /etc/apache2/sites-available/NAME_OF_YOUR_HOST.conf).

Thank you.

**Comment by KonzeptAcht** [comment]
Hello @ruslanbaidan 

The problem is that we do not use the Cases.lu model prepared by you. We have now developed our own procedure, which results in about 700 links in the knowledge database that do not correspond to the model. We have already had a very extensive exchange with Cederic on this model in the above mentioned tickets. He should have a good overview of the model we use by now. You can also have a look at our rusted instance. Here the problem is also present.

Problem number 1 is solved. I had to increase the PHP memory limit up to 1GB. Now the exports work. 

Problem number 2 is still open. Therefore I moved a Business Unit (with some links) from the Asset Library to the Risk Analysis (Drag&Drop) 

As error in apache2 error.log

[Thu Feb 13 12:51:23.049311 2020] [mpm_prefork:notice] [pid 26844] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1d configured -- resuming normal operations
[Thu Feb 13 12:51:23.049372 2020] [core:notice] [pid 26844] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 13 12:58:37.066730 2020] [php7:error] [pid 26870] [client XXX.XXX.XXX.XXX:51815] PHP Fatal error:  Maximum execution time of 360 seconds exceeded in /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 710, referer: [DOMAIN] 

We have already modified the php.ini and increased the memory limit to 360 seconds.

/etc/php/7.3/apache2/php.ini
      max_input_time = 360

**Comment by cedricbonhomme** [comment]
Did you try to increase the maximum execution time:
https://github.com/monarc-project/MonarcAppFO/blob/master/vagrant/bootstrap.sh#L18 ?
With a higher value.

Maximum input time [is different](https://www.php.net/manual/en/info.configuration.php#ini.max-input-time).

**Comment by KonzeptAcht** [comment]
Yes, we increased both up to 360s as you can see in the log

**Comment by ruslanbaidan** [comment]
Did you try to upgrade the version to the latest one 2.9.10?

**Comment by KonzeptAcht** [comment]
Yes, we have updated to 2.9.10

**Comment by ruslanbaidan** [comment]
Could you send to us your expanded library assets hierarchy image, we can see how big is it and try to reproduce something similar (my email is ruslan.baidan@cases.lu)
Meanwhile, could you also try to increase the max_execution_time to 600 (10 mins), or set to 0 (unlimited), to see if the operation will be finished.

**Comment by KonzeptAcht** [comment]
Send you a mail @ruslanbaidan

**Comment by KonzeptAcht** [comment]
With max_execution_time 0 I still get the corresponding error code

[Thu Feb 13 15:13:38.754728 2020] [php7:error] [pid 28735] [client XXX.XXX.XXX.XXX:54203] PHP Fatal error:  Maximum execution time of 0 seconds exceeded in /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 710, referer: [DOMAIN]

**Comment by KonzeptAcht** [comment]
Thanks for the great work
