### ISSUE TITLE
Use a better encryption method for the export of objects and analysis

### ISSUE THREAD

**Issue by cedricbonhomme** [monarc-project/MonarcAppFO#260]
**Is your feature request related to a problem? Please describe.**
The export of objects and the risk analysis can be encrypted by the backend if the user specifies a password.
Currently MONARC is using AES-256-ECB as encryption algorithm and md5 to hash the password entered by the user.

ECB should not be used if encrypting more than one block of data with the same key and is rarely used today in this kind of context.

We should use instead AES-256-CBC / sha512. Of course the new implementation must support old export of objects and analysis.

**Comment by ruslanbaidan** [comment]
Not released yet.

**Comment by jfrocha** [comment]
Released on [v2.9.12](https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.9.12)
