### ISSUE TITLE
Create a risk analysis (FO) from a model (BO) with information risks

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#264]
**Describe the bug**
Creating a risk analysis, from a model in BO containing information risks -> the information risks are not created in the analysis

**To Reproduce**
1. Go to BO
2. Create a model : 
![image](https://user-images.githubusercontent.com/18661517/78540938-26363100-77f5-11ea-8b7c-f4a12b464ea7.png)

3. Go to FO and create a risk analysis from the model
![image](https://user-images.githubusercontent.com/18661517/78541126-6d242680-77f5-11ea-9e4d-aee124e786b1.png)

**Expected behavior**
The risks must be instantiated

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 |  Ubuntu, ...
| OS version (client)                   |  Win10, 
| PHP version                             | 7.2
| MONARC version / git hash     | 2.9.12, hash of the commit
| Browser                                    | , Chrome,

**Comment by ruslanbaidan** [comment]
It seems the issue was with specific risks.
Now it works. Informational and operational risks are taken as well as evaluations.
