### ISSUE TITLE
Develop the structure of the statistics database and models

### ISSUE THREAD

**Issue by ruslanbaidan** [monarc-project/MonarcAppFO#269]
We need to develop the FrontOffice database schema to collect and serve the statistics data for the dashboard.
The structure should meet the following criteria:
- The time view chart will show the evolution by analysis and total aggregated for all of them.
- The statistics will relate to the first 4 tabs of the dashboard (risk, threats, vulnerabilities, number of risk on threshold risk levels).
- History of the data used for statistics in order to have a view on the evolution of the analysis.
- The stats can be collected once per week or on daily basis. It also includes the snapshots.

**Comment by ruslanbaidan** [comment]
Related to the epic: https://github.com/monarc-project/MonarcAppFO/issues/269

**Comment by cedricbonhomme** [comment]
> The stats can be collected once per week or on daily basis. It also includes the snapshots.
Maybe we need a new PHP console command. Which will be launched via a CRON task. If need it would be possible to configure this cron task (or command parameters) via the local.php file, so per instance.

**Comment by ruslanbaidan** [comment]
> > The stats can be collected once per week or on daily basis. It also includes the snapshots.
> 
> Maybe we need a new PHP console command. Which will be launched via a cron task. If needed it would be possible to configure this cron task (or command parameters) via the local.php file, so per instance.

That's definitely needed and can be started in parallel. I'll create a ticket.
