### ISSUE TITLE
Problem when a label of an impact contains a character such as '&' or '%'

### ISSUE THREAD

**Issue by cedricbonhomme** [monarc-project/MonarcAppFO#27]
The generation of the report is broken (at step 3) when a label of an impact contains a character such as '&' or '%'.

**Comment by cedricbonhomme** [comment]
Same thing with the character '>'

**Comment by jfrocha** [comment]
I'd fixed issue for asset names (didn't still commit)
Look up
_WT function in [DeliverableGenerationService.php:1641](https://github.com/monarc-project/zm-client/blob/master/src/MonarcFO/Service/DeliverableGenerationService.php)

Just, there remains fields of deliverable generation form.

[ApiAnrDeliverableController.php:39](https://github.com/monarc-project/zm-client/blob/master/src/MonarcFO/Controller/ApiAnrDeliverableController.php)

**Comment by cedricbonhomme** [comment]
Excellent! I'll test that! I think we can also replace the characters in the params from the generqation form
