### ISSUE TITLE
Create a command of statistics aggregation

### ISSUE THREAD

**Issue by ruslanbaidan** [monarc-project/MonarcAppFO#270]
We need to create a PHP console command, that will be launched via a cron task.

The stats aggregation parameters needs to be configured per instance.

The expected configuration parameters suppose to be setup/changed by the "instance administrator":
- list of analyses to include in the stats (_all by default_).
- switch on/off the stats aggregation (_on by default_)
- allow/prevent statistics sharing to the BackOffice. (should be a description of what exactly is shared) (_allow by default_)

We should store them in the database (statistics_settings)

**Comment by ruslanbaidan** [comment]
Linked to the epic: https://github.com/monarc-project/MonarcAppFO/issues/268

**Comment by cedricbonhomme** [comment]
Parameters - WIP:

- list of analysis to include. If empty, it should include everything
