### ISSUE TITLE
"Edit impacts" in version 2.9.13

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#273]
**Describe the bug**
In the current MONARC version 2.9.13 it is not possible to edit the impact of one global asset, which should not inherit the impact from the primary asset. The following error message appears:

**To Reproduce**
1. Open existing risk analysis 
2. Select a global Asset from risk analysis 
3. Select "Edit impacts"
4. Change impacts
5. get error

Version 2.9.12 is not affected.

**Expected behavior**
![Alt text](https://www.konzeptacht.de/wp-content/uploads/2020/04/impacts-error-monarc2913.png)

**Screenshots**

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04
| OS version (client)                   | MacOS, Win10
| PHP version                             | 7.3
| MONARC version / git hash     | 2.9.13
| Browser                                    | Firefox, Chrome, Safari

**Comment by ruslanbaidan** [comment]
Fix for the issue: https://github.com/monarc-project/zm-core/pull/35
