### ISSUE TITLE
Duplicate assets

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#279]
**Describe the bug**
When trying to publish an asset with multiple linked assets, you will receive an error message.
If you try to duplicate an asset with only one linked asset, the linked asset will be duplicated, but not the selected.

**To Reproduce**
1. select an existing risk analysis or create a new one.
2. Link to or more existing assets inside the asset library. Duplicate one asset with some linked assets.
3. Get error message or duplicate wrong item
**Expected behavior**
Duplicate the selected asset

**Screenshots**
Duplication with multiple linked assets
![Alt text](https://www.konzeptacht.de/wp-content/uploads/2020/04/duplicate-asset-monarc-error2913.png)
Duplication of asset with one link
![Alt text](https://www.konzeptacht.de/wp-content/uploads/2020/04/duplicate-wrong-item-monarc2913.png)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04
| OS version (client)                   | MacOS, Win10
| PHP version                             | 7.3
| MONARC version / git hash     | 2.9.13
| Browser                                    | Firefox, Chrome, Safari

**Comment by ruslanbaidan** [comment]
Related PR: https://github.com/monarc-project/zm-core/pull/36
