### ISSUE TITLE
Edit Impact fails

### ISSUE THREAD

**Issue by vlabmichl** [monarc-project/MonarcAppFO#280]
**Describe the bug**
During todays online training i experiences the following bug on my local VM:
* Editing impacts fails with the following red error note:
```
An error occurred while fetching api/client-anr/1/instances/39: Argument 1 passed to Ramsey\Uuid\Uuid::isValid() must be of the type string, array given, called in /var/lib/monarc/fo/vendor/monarc/core/src/Service/AbstractService.php on line 586 (500)
```

The asset I tried to edit is positioned in the 2nd hierarchy level of the assessment project.
```
Project
|
-- Level 1
  | 
  -- Level 2 (here)
```

**Expected behavior**
Override of the inherited C-I-A values of the parent asset.

**Screenshots**
Not possible as the red box goes away too fast.

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | VirtualBox with official VM
| OS version (client)                   | MacOS
| MONARC version / git hash     | 2.9.13
| Browser                                    | Firefox

**Comment by ruslanbaidan** [comment]
Could you please use the image from v.2.9.14
https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.9.14
We fixed the issue in the newer version.

**Comment by vlabmichl** [comment]
Thank you. Works for me now.
