### ISSUE TITLE
Impossible to export an analysis when a user has deleted a category of a measure

### ISSUE THREAD

**Issue by cedricbonhomme** [monarc-project/MonarcAppFO#282]
**Describe the bug**
If the user delete a category of a measure via the knowledge base, it won't be possible anymore to export the whole analysis.

**To Reproduce**
1. Go to the knowledge base, in the security referential tab
2. Edit a measure, delete the categoy
3. Try to export the analysis.

**Expected behavior**
The export of the analysis should be returned, event if the category of the measure has been deleted (in the entities categories of Measures are nullable).

**Comment by cedricbonhomme** [comment]
monarc-project/zm-core/pull/37

**Comment by ruslanbaidan** [comment]
Fixed in https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.9.15
