### ISSUE TITLE
"Evaluation of Trends and Threat, and synthesis" no propability

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#284]
**Describe the bug**
For MONARC databases updated from older MOARC versions, the "Evaluation of Trends and Threat, and synthesis" in the "Threats assessment" section offers two more lines for the "probability".

In risk analyses that are newly created in version 2.9.14, this “probability” is no longer available. This behavior affects our own installation as well as our instance in my.monarc.lu.

**To Reproduce**
1. Open Step 1 "Evaluation of Trends and Threat, and synthesis" and select "Threats assessment
"
2. in older risk analyses there is the possibility to make a probability assessment
3. in newer versions "after 2.9.14" this option is no longer available

**Expected behavior**
There is the possibility to carry out a probability assessment

**Screenshots**
Older risk analyses
![alt text](https://www.konzeptacht.de/wp-content/uploads/2020/05/evaluation_error_01.png)

Newer risk analyses
![alt text](https://www.konzeptacht.de/wp-content/uploads/2020/05/evaluation_error_02.png)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu LTS 18.04
| OS version (client)                   | MacOS, Win10
| PHP version                             | 7.3
| MONARC version / git hash     | 2.9.14
| Browser                                    | Firefox, Chrome, Safari

**Comment by jerolomb** [comment]
Hello,

Excepting a bug if you want to see the probability line, you have to tick the "definition of the risk evaluation criteria" 

![image](https://user-images.githubusercontent.com/18661517/81391387-4707e400-911d-11ea-8551-3cec817df69c.png)

I hope, it helps

**Comment by KonzeptAcht** [comment]
Okay, thanks for the advice @jerolomb . We've just reproduced this.However, we do not believe it is useful to pre-empt a hook in a downstream step. Since no one will then make a probability assessment after they have already completed the step for themselves.

**Comment by jerolomb** [comment]
it's just because the scale of the probability is defined in this steps, and if you set a probability you can't change anymore the scales. Thanks for your feedback.

**Comment by KonzeptAcht** [comment]
It is currently problematic mainly because this does not correspond to the procedure of the web interface and the procedure trained by you. Would it not be possible to at least display the probability evaluation function, grey it out and provide a hint why this part cannot yet be edited?

**Comment by tkochanek-K8** [comment]
How about changing the order of sub-processes?
- Risks analysis context
- Risks management organisation
- Definition of the risk evaluation criteria
- Evaluation of Trends and Threat, and synthesis

And everything is fine again.. :-)

**Comment by cedricbonhomme** [comment]
Yes, it would be a solution.

An other solution is to display it, but in a first step disable it (it will be greyed).  Then when "definition of the risk evaluation criteria" is ticked it will be accessible.

**Comment by KonzeptAcht** [comment]
@cedricbonhomme Could you reopen the ticket then?

**Comment by ruslanbaidan** [comment]
Originally the ticket has been created as a bug, but as we found this is a new functionality.
Created a feature request: https://github.com/monarc-project/MonarcAppFO/issues/292

**Comment by KonzeptAcht** [comment]
Ok, thanks @ruslanbaidan
