### ISSUE TITLE
Translation "vulnerabilities" in risk analysis

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#286]
**Describe the bug**
In the risk analysis overview, the English word "vulnerabilities" is not correctly translated. In the German version, "Schwachstellen" should also be shown here instead of "Sicherheitsrisiko".

**To Reproduce**
1. Open a risk analysis

**Expected behavior**
"vulnerabilities" should be translated as "Schwachstellen"

**Screenshots**
![alt text](https://www.konzeptacht.de/wp-content/uploads/2020/05/vulnerablilities_error_01.png)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu LTS 18.04
| OS version (client)                   | MacOS, Win10
| PHP version                             | 7.3
| MONARC version / git hash     | 2.9.14
| Browser                                    | Firefox, Chrome, Safari

**Comment by ruslanbaidan** [comment]
The fix will be available in the next release.
