### ISSUE TITLE
Two-factor authentication 

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#288]
**Is your feature request related to a problem? Please describe.**
Many of our customers' MONARC instances are freely accessible via the Internet. This means that these systems are vulnerable to brute force attacks. 

**Describe the solution you'd like**
Is it possible to secure authentication using a two-factor system such as TOTP?

**Comment by cedricbonhomme** [comment]
Adding support of WebAuthn is interesting.
But ould you prefer a solution via U2F device (OATH – TOTP) like with the Yubikeys/solokeys.com or via a one time password authenticator (Google Authentication - with a server) ?

**Comment by KonzeptAcht** [comment]
In my opinion, both approaches would be very interesting. However, I suspect that an implementation using one time password authenticator (Google Authentication) would be more useful, since it addresses the larger dimensions. For this kind of authentication you can simply download a smartphone app.

**Comment by cedricbonhomme** [comment]
https://github.com/monarc-project/ng-client/pull/39
