### ISSUE TITLE
Matched referentials cannot be unlinked

### ISSUE THREAD

**Issue by n1x0d** [monarc-project/MonarcAppFO#289]
**Describe the bug**
A referential once matched to another cannot be unlinked.

**To Reproduce**
1. Knowledge Base, Referentials View
2. Add a new referential
3. Add a new control
4. Click on match referentials
5. Match a referential to another
6. Try and unlink the referential. It will be gone from the view. Close the view and click on match referentials again. Referentials are still linked. Delete again, open again, still there. 

**Expected behavior**
A reference once deleted (unlinked) should not reappear.

**Comment by n1x0d** [comment]
It's not critical, as you can just delete the control and recreate it. Then link it again.

**Comment by cedricbonhomme** [comment]
https://github.com/monarc-project/zm-client/pull/35

**Comment by ruslanbaidan** [comment]
Fixed in https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.9.15
