### ISSUE TITLE
Improvements and fixes for German translations

### ISSUE THREAD

**Issue by cedricbonhomme** [monarc-project/MonarcAppFO#293]
Below are some contributions of a MONARC user that aims to improve the German translations.

1. Replace "Ein Schwachstelle hinzufügen" with "Eine Schwachstelle hinzufügen"
2. Replace "Alle Modelle müssen Werttyp, Bedrohung und Schwachstelle gemeinsam sein" with "Alle Modelle müssen Werttyp, Bedrohung und Schwachstelle gemeinsam haben"
3. Replace "Soll das Schwachstelle wirklich gelöscht werden?" with "Soll die Schwachstelle wirklich gelöscht werden?"
4. Replace "Importieren Sie ein Schwachstelle von MOSP" with "Importieren Sie eine Schwachstelle von MOSP"
5. Replace "Kein Ihrer Suche entsprechendes Schwachstelle gefunden" with "Keine Ihrer Suche entsprechende Schwachstelle gefunden"
6. Replace "Ein Modell muss Werttyp, Bedrohung und Schwachstelle gemeinsam sein" with "Ein Modell muss Werttyp, Bedrohung und Schwachstelle gemeinsam haben"
7. Replace "Empfehlung, die eine fest zugeordnete Aktion zur Lösung eines " with "Empfehlung, die eine fest zugeordnete Aktion zur Lösung einer "
8. Replace "Tuple-Werttyp/Bedrohung/Schwachstelle ist ungültig" with "Tupel-Werttyp/Bedrohung/Schwachstelle ist ungültig"
9. Replace "Das Schwachstelle wurde erfolgreich erstellt, jedoch ohne Modelle, das " with "Die Schwachstelle wurde erfolgreich erstellt, jedoch ohne Modelle, das "
10. Replace "Das Schwachstelle wurde erfolgreich erstellt." with "Die Schwachstelle wurde erfolgreich erstellt."
11. Replace "Das Schwachstelle wurde gelöscht." with "Die Schwachstelle wurde gelöscht."
12. Replace "Das Schwachstelle wurde erfolgreich bearbeitet, jedoch ohne Modelle, das " with "Die Schwachstelle wurde erfolgreich bearbeitet, jedoch ohne Modelle, das "
13. Replace "Sie müssen ein Schwachstelle auswählen" with "Sie müssen eine Schwachstelle auswählen"

**Comment by tkochanek-K8** [comment]
Dear Cédric,
we have seen that there is an overview of the improvements in the German translation.
Would you think about replacing "WE" (weggelassen) by "n.a." (nicht anwendbar) in the statement of applicability? Also in the English translation "n.a." (not applicable) could be used here as well instead of "EX" (excluded).  That makes the questions in ISO 27001 certifications easier.
Many thanks for your continuous engagement.
Best regards,
Thomas

**Comment by cedricbonhomme** [comment]
Hi,

I do not really get. Is this another translation issue ?
Because in the norm "EX" (excluded) is used.

**Comment by tkochanek-K8** [comment]
You are absolutely right, the standard says that in SoA controls can be "excluded".
In ISO 27001 audits, however, "excluded" often is associated with the fact that these controls are no longer considered. It would be a simple optimization of the translation to use "not applicable" or "nicht anwendbar", as this is the common saying. But this optimization is certainly of very low priority. :-)
