### ISSUE TITLE
Dashboard Diagrams "No Data" 2.9.14

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#294]
**Describe the bug**
As in a previous version there are again problems with the dashboards.

For risk analyses from version 2.9.14 on, you get the error message "No Data Available" or no display at all under "Dashboard". The error image can be adjusted in my.monarc.lu, but not in the VM.

Browser Console Output:
`Possibly unhandled rejection: undefined angular-common-libs.js:127:303`
`    Angular 7`
`        e`
`        get`
`        g`
`        $digest`
`        evalAsync`
`        completeTask`
`        d`

**To Reproduce**
1. Create new Risk analysis with monarc 2.9.14
2. Create Assets and evaluate them
3. After completion of step 3
4. Open Dashboard
5. See error

**Expected behavior**
The results of the completed risk analysis should be displayed graphically.

**Screenshots**
![monarc-diagramm-1](https://user-images.githubusercontent.com/47662401/83149203-21f20a00-a0fa-11ea-9c4a-9b22c37e1b6e.PNG)
![monarc-diagramm-2](https://user-images.githubusercontent.com/47662401/83149224-25859100-a0fa-11ea-9d08-a4ebac0495e9.PNG)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu Server LTS 18.04
| OS version (client)                   | MacOS, Win10
| PHP version                             | 7.3
| MONARC version / git hash     | 2.9.14
| Browser                                    | Firefox, Chrome, Safari

**Comment by jerolomb** [comment]
Thanks for the description, we are on it.

**Comment by jfrocha** [comment]
Bugfix commits:
https://github.com/monarc-project/ng-anr/commit/e98ca0d9e5053ac083be5b5ae9cabdae709c5c70
https://github.com/monarc-project/ng-client/commit/9d3dc4b8d45a2780c45427567ae577542fb7ac24

**Comment by ruslanbaidan** [comment]
Fixed in https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.9.15
