### ISSUE TITLE
Risk treatment plan comment delete date

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#298]
**Describe the bug**
If a comment is deleted in the risk treatment plan and the page is reloaded, the date of the action is also missing

**To Reproduce**
1. Go to step 4 "Implementation of the risk treatment plan"
2. delete a comment from one of the filled out comment fields
3. go back to risk analysis
4. go to step 4 "Implementation of the risk treatment plan" again
5. the date and the comment field of the selected measure are deleted

**Expected behavior**
Only the comment field is empty and the entered date remains

**Screenshots**
![risk_treatment_plan_comment](https://user-images.githubusercontent.com/47662401/85127490-cfef6080-b22f-11ea-93b9-ebeeda817195.PNG)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04 LTS
| OS version (client)                   | MacOS, Win10
| PHP version                             | 7.3
| MONARC version / git hash     | 2.9.15
| Browser                                    | Firefox, Chrome, Safari

**Comment by cedricbonhomme** [comment]
This fix will be as well present in the next release.
