### ISSUE TITLE
Organization's contact e-mail refused based on top-level domain

### ISSUE THREAD

**Issue by Tichod** [monarc-project/MonarcAppFO#299]
**Describe the bug**
Organization's contact email with .security top-level domain is refused 

**To Reproduce**
1. Go to 'Home > Administration > Organization'
2. Enter following email address for contact address 'xxx@xxx.security'
3. Contact email highlighted red, can't click on 'Update organization'

**Expected behavior**
Email address should be accepted, .security being a valid generic top-level domain.
Besides, xxx@xxx.securit is accepted, even if .securit is not a valid TLD.

**Screenshots**
Cf. screenshot of refused addres (left), and accepted adress (right)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04.4
| OS version (client)                   | Win10
| PHP version                             | 7.2.24
| MONARC version / git hash     | 2.9.15 (virtual machine)
| Browser                                    | Firefox and Chrome

![MONARC-Contact_email_refused](https://user-images.githubusercontent.com/18058781/85718122-7f27ae00-b6ee-11ea-8112-18dca4201720.png)

**Additional context**
xxx@xxx.security address is accepted for my MONARC user account

**Comment by cedricbonhomme** [comment]
Hello,
thank you for this report. You are correct. In fact there is a limit set to 7 characters. This will be fixed.

**Comment by Tichod** [comment]
Thank you for your answer.
And thank you for the awesome work!

**Comment by Tichod** [comment]
It works now (MONARC 2.9.16).
Thank you !
