### ISSUE TITLE
Read Only User logout during risk treatment

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#300]
**Describe the bug**
Users with read-only authorization are logged off when editing risk treatment.

**To Reproduce**
1. Log in as User with read-only access to an existing risk analysis
2. select an information risk and click the link to risk treatment
3. use button "Back to the List"
4. the user is logged out and redirected to the login page

**Expected behavior**
The user is returned to the risk analysis

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04 LTS
| OS version (client)                   | MacOS, Win10
| PHP version                             | 7.3
| MONARC version / git hash     | 2.9.15
| Browser                                    | Firefox, Chrome, Safari

**Comment by cedricbonhomme** [comment]
The fix will be included in the next release.

**Comment by ruslanbaidan** [comment]
PRs:
https://github.com/monarc-project/ng-anr/pull/14
https://github.com/monarc-project/ng-client/pull/14
