### ISSUE TITLE
Error when calling risk treatment plan display

### ISSUE THREAD

**Issue by Tichod** [monarc-project/MonarcAppFO#301]
**Describe the bug**
Error message when clicking on any of the following cases:
-  '3 Evaluation and treatment of risks >Risk treatment plan management'

- '4 Implementation and monitoring >Management of the Implementation of the risk treatment plan'

**To Reproduce**
1. Import [risk analysis demo file](https://www.monarc.lu/assets/files/monarc-training/fr/MyPrintFR.json) in new risk analysis
2. Click on '3>Risk treatment plan management' (case 1) or '4>Management of the Implementation of the risk treatment plan' (case 2)
3. Empty 'Risk treatment plan management' table appears (case 1), or no table (case 2)
4. See error message, identical in both cases

**Expected behavior**
The 'Risk treatment plan management' or the 'Management of the risk treatment plan' is displayed.

**Screenshots**
Cf. screenshot of error message, identical in both cases

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04.4
| OS version (client)                   | MacOS, Win10, Ubuntu, ...
| PHP version                             | Win10
| MONARC version / git hash     | 2.9.15 (virtual machine)
| Browser                                    | Firefox, Chrome

**Additional context**
No additional context
![2020_07_02-MONARC-Erreur-Implementation_plan_trtmt_risques](https://user-images.githubusercontent.com/18058781/86359120-e6a2a800-bc70-11ea-8ff1-223a9e532e39.png)

**Comment by cedricbonhomme** [comment]
Thank you for the report.
This is fixed, it was supposed to be already fixed but it seems we made a mistake when merging... We are about the update the release and the VirtualBox OVA file which is available on the [GitHub releases page](https://github.com/monarc-project/MonarcAppFO/releases/latest).

**Comment by cedricbonhomme** [comment]
The new VM has been uploaded:
https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.9.15

**Comment by Tichod** [comment]
Thank you (with a >2 months delay!)
