### ISSUE TITLE
Demo VM requires vagrant credentials

### ISSUE THREAD

**Issue by jerome2lux** [monarc-project/MonarcAppFO#308]
Hi,

I have tried to use the MONARC VM following [these instructions](https://www.monarc.lu/download/#virtual-machine).
When I boot the VM, I am asked for a vagrant login. I do not think it is planned to be so.

I have tried admin/admin but it is not working.

![Capture d’écran 2020-08-19 à 10 39 53](https://user-images.githubusercontent.com/47412609/90612439-5280a600-e208-11ea-9390-0118f1ea7124.png)

**Comment by ruslanbaidan** [comment]
Hello,
Normally you don't need to login to your VM. It can be used only to know your `$ ip address`.
The login name is "monarc", and password is "password", which are specified on each release page, e.g.
https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.9.15 (SSH login).
