### ISSUE TITLE
Detaching of recommendations doesn't work

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#314]
**Describe the bug**
When detaching a recommendation from a risk, the green message says it's ok but it isn't

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to MONARC
2. Import MyPrint for example
3. Try to detach a recommendation

**Expected behaviour**
The recommendation should be detached

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 |  Ubuntu, 
| OS version (client)                   |  Win10,  
| PHP version                             | 7.2
| MONARC version / git hash     | 2.9.16, 
| Browser                                    |  Chrome

**Additional context**
tested on formation and reported from a customer of our cloud by email. It also doesn't work with risk analysis created from scratch

**Comment by ruslanbaidan** [comment]
PR:
https://github.com/monarc-project/zm-core/pull/43
