### ISSUE TITLE
Record of processing activities creation from an existing

### ISSUE THREAD

**Issue by jfrocha** [monarc-project/MonarcAppFO#315]
**Describe the bug**
Fails creating new record from existing
**To Reproduce**
1. Go to create record
2. Click on "Search a processing to create one from an existing"
3. Select existing record
4. Click on create

**Console error**
 "Call to undefined method Monarc\FrontOffice\Model\Entity\Record::setUpdatedAt()"

stacktrace: "#0 /var/lib/monarc/MonarcAppFO/vendor/monarc/frontoffice/src/Controller/ApiAnrRecordDuplicateController.php(35): Monarc\FrontOffice\Service\AnrRecordService->duplicateRecord(79, 'tr2')

**Desktop**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| MONARC version / git hash     | 2.9.16
| Browser                                    | Chrome

**Comment by ruslanbaidan** [comment]
PR:
https://github.com/monarc-project/zm-client/pull/41
