### ISSUE TITLE
Implement the UI language management

### ISSUE THREAD

**Issue by jfrocha** [monarc-project/MonarcAppFO#318]
**Description**

As a part of the planned in the roadmap: "Improving translation management" (https://github.com/monarc-project/MonarcAppFO/wiki/Roadmap) we need a UI (front-end) translation system.

The system allows us and external contributors to add new languages and improve the existing translations.

The criteria of the solution is an open source platform.

**Comment by ruslanbaidan** [comment]
Platform: Weblate
https://translate.monarc.lu/
