### ISSUE TITLE
ANR_DOES_NOT_EXIST Error while creating new users

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#319]
**Describe the bug**
When creating new users, an error occurs when assigning authorizations for existing risk analyses. Creating users without authorization for risk analyses works. According to the error message, the selected risk analysis is not found. ('id'='10' is the selected risk analysis for which read permissions should be assigned)
This error also occurs in the my.monarc environment.

**To Reproduce**
1. Log in as administrator
2. got to "manage users"
3. add user and assign "read" or "read and write" permissions to an existing risk analysis
4. click create
5. error occures

**Expected behavior**
Creating a user with the assigned permissions

**Screenshots**
![MONARC ANR_User Creation Error](https://user-images.githubusercontent.com/47662401/101761418-68c6b080-3adc-11eb-8d78-2fcbf804eef1.PNG)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04 LTS
| OS version (client)                   | MacOS, Win10, Debian
| PHP version                             | 7.4
| MONARC version / git hash     | 2.9.16
| Browser                                    | Firefox, Chrome, Safari

**Additional context**

Error Message from Browser Console

`Possibly unhandled rejection: {"data":{"errors":[{"message":"Data validation errors: [ {\"anrs\":{\"ANR_DOES_NOT_EXIST\":\"Anr with the ID (array (\\n  'id' => '10',\\n  'rwd' => 1,\\n)) does not exist.\"}}","error":"error-exception","exception":{"class":"Monarc\\Core\\Exception\\Exception","file":"/var/lib/monarc/fo/vendor/monarc/frontoffice/src/Controller/ApiAdminUsersController.php","line":67,"message":"Data validation errors: [ {\"anrs\":{\"ANR_DOES_NOT_EXIST\":\"Anr with the ID (array (\\n  'id' => '10',\\n  'rwd' => 1,\\n)) does not exist.\"}}","stacktrace":"#0 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(467): Monarc\\FrontOffice\\Controller\\ApiAdminUsersController->create(Array)\n#1 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(428): Laminas\\Mvc\\Controller\\AbstractRestfulController->processPostData(Object(Laminas\\Http\\PhpEnvironment\\Request))\n#2 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\\Mvc\\Controller\\AbstractRestfulController->onDispatch(Object(Laminas\\Mvc\\MvcEvent))\n#3 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\\EventManager\\EventManager->triggerListeners(Object(Laminas\\Mvc\\MvcEvent), Object(Closure))\n#4 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(105): Laminas\\EventManager\\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\\Mvc\\MvcEvent))\n#5 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(312): Laminas\\Mvc\\Controller\\AbstractController->dispatch(Object(Laminas\\Http\\PhpEnvironment\\Request), Object(Laminas\\Http\\PhpEnvironment\\Response))\n#6 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\\Mvc\\Controller\\AbstractRestfulController->dispatch(Object(Laminas\\Http\\PhpEnvironment\\Request), Object(Laminas\\Http\\PhpEnvironment\\Response))\n#7 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\\Mvc\\DispatchListener->onDispatch(Object(Laminas\\Mvc\\MvcEvent))\n#8 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\\EventManager\\EventManager->triggerListeners(Object(Laminas\\Mvc\\MvcEvent), Object(Closure))\n#9 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\\EventManager\\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\\Mvc\\MvcEvent))\n#10 /var/lib/monarc/fo/public/index.php(34): Laminas\\Mvc\\Application->run()\n#11 {main}"}}]},"status":400,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","data":{"firstname":"TestUser","lastname":"Test","email":"*****@*****.de","role":["userfo"],"anrs":[{"id":"10","rwd":1}]},"url":"api/users","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","token":"8c80a3b940c44d93b4dbfb8a560b768e75ad48b7b2ebd99e91e976e2a86ec125048d5eb35fd1f679445db0.65601243"},"cached":false},"statusText":"Bad Request","xhrStatus":"complete","resource":{"firstname":"TestUser","lastname":"Test","email":"*****@*****.de","role":"...","anrs":"..."}}`

**Comment by KonzeptAcht** [comment]
Brief Update,

Creating users without permissions on an existing risk analysis works. The later assignment of authorizations also works.

**Comment by ruslanbaidan** [comment]
Thank you for the report. 
The issue is fixed and will be added to the release v2.10.1
As far as the release is not announced yet but on our productions already, we are going to add the fix as well.
The PR is here: https://github.com/monarc-project/zm-client/pull/48

**Comment by ruslanbaidan** [comment]
The fix is deployed to our prod and available in the master branch of the repo.
You need to pull the main project and run `composer ins` or `composer up`.
