### ISSUE TITLE
Lost operationnal risk when importing from MONARC Common DB 

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#32]

**Comment by jerolomb** [comment]
it seems to be linked to https://github.com/monarc-project/zm-core/blob/master/src/MonarcCore/Service/ObjectExportService.php L111

**Comment by cedricbonhomme** [comment]
it seems that this was done in the past: https://github.com/monarc-project/zm-core/commit/0377c116104eeab41620d4fdd4bffa4269ed975a#diff-cf84f28c5d37a982218f45fcba6312c4
I will try

**Comment by jerolomb** [comment]
LoL if it works it's cool.

**Comment by cedricbonhomme** [comment]
I hope. The import/export code is here:
https://github.com/monarc-project/zm-core/commit/fe972ba618f4cee6f8044d8ebb5a52d7de141120#diff-cf84f28c5d37a982218f45fcba6312c4

**Comment by cedricbonhomme** [comment]
here is a potential fix: https://github.com/monarc-project/zm-core/commit/29493acaa9963fd474092938f2433a1938d64181
mo strange behavior om my side

**Comment by cedricbonhomme** [comment]
seems to be solved
