### ISSUE TITLE
missing png export from dashboard

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#323]
**Is your feature request related to a problem? Please describe.**
For management reviews, we previously used the feature to export dashboard graphics directly as PNG. This is no longer possible since 2.10.1.

**Describe the solution you'd like**
Resumption of the functionality to generate PNGs

**Describe alternatives you've considered**
Export the graphics as PPTX and then save as PNG

**Additional context**
-/-

**Comment by ruslanbaidan** [comment]
The functionality was not removed in the new version.
It works well on our production servers on the version 2.10.1 and also on 2.9.16.

Please check the correct button, which is used to download a chart as a .png file:
https://www.monarc.lu/documentation/user-guide/#dashboard
I also attached a screenshot.
<img width="1649" alt="ExportToPng" src="https://user-images.githubusercontent.com/3246171/104776537-87beff00-577a-11eb-85e1-c93721f69c1a.png">

You probably need to check your browser permissions as well.
It's possible that it blocks downloading of .png files.
