### ISSUE TITLE
Snapshot restore 

### ISSUE THREAD

**Issue by jfrocha** [monarc-project/MonarcAppFO#326]
**Describe the bug**
Restoring a snapshot, get this error:

```json
angular-common-libs.js:129 Possibly unhandled rejection: {"data":{"errors":[{"message":"Call to undefined method Monarc\\FrontOffice\\Model\\Table\\UserAnrTable::findById()","error":"error-exception","exception":{"class":"Error","file":"/var/lib/monarc/fo/vendor/monarc/frontoffice/src/Service/SnapshotService.php","line":188,"message":"Call to undefined method Monarc\\FrontOffice\\Model\\Table\\UserAnrTable::findById()"
```

**To Reproduce**
1. Go to snapshot view
2. Restore a snapshot 
3. See error

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 |  Ubuntu, ...
| MONARC version      | 2.10.1
| Browser                                    | Chrome

**Comment by ruslanbaidan** [comment]
PR:
https://github.com/monarc-project/zm-client/pull/49/files
