### ISSUE TITLE
Garbled screen with certain navigators after logging in

### ISSUE THREAD

**Issue by Tichod** [monarc-project/MonarcAppFO#327]
**Describe the bug**
When logging in the web interface in Mozilla Firefox or Microsoft Edge, the resulting display is garbled and unusable: a small rectangle squashed top left of the overall navigator window.

**To Reproduce**
0. Update MONARC from 2.9.16 to 2.10.1 (don't know if related, but error appeared after that)
1. Open login screen in Mozilla Firefox or Microsoft Edge.
2. Enter credentials, then click 'Log in'.
3. See error on screen copy

**Expected behavior**
The user session opens and occupies all available navigator window.

**Screenshots**
Cf. attached file.

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 20.04.2
| OS version (client)                   | Win10
| PHP version                             | 7.4.3
| MONARC version / git hash     | 2.10.1 (virtual machine)
| Browser                                    | Firefox 85.0 or Edge 88.0.705.56

**Additional context**
*** Accessing the user session with Chrome 88.0.4324.104 or 88.0.4324.146 works correctly.
*** With Internet Explorer, the display is garbled differently, right in the logon screen. I opened a separate report for this:  #328.
![2021_02_02-MONARC_UI_error-Edge](https://user-images.githubusercontent.com/18058781/106752424-b9fda700-662a-11eb-8687-fb4487f2efb0.png)
![2021_02_02-MONARC_UI_error-Firefox](https://user-images.githubusercontent.com/18058781/106752427-ba963d80-662a-11eb-82b4-e4cf6b04ed96.png)

**Comment by KonzeptAcht** [comment]
Hello @Tichod,
I have been able to reproduce this problem a few times. A simple workaround is to backup the local.php, reinstall the file structure and import the local.php again. Then run the update script again.

A deletion of the server-side cache under data/cache, 
data/DoctrineORMModule/Proxy/ and data/LazyServices/Proxy/ does not help.

I hope the experience helps.

**Comment by ruslanbaidan** [comment]
As mentioned by @KonzeptAcht , the issue is probably related to the missing lines in your config file.
Please make sure that you have the following configuration:
https://github.com/monarc-project/MonarcAppFO/blob/master/config/autoload/local.php.dist#L79-L82

If you would like to use StatsService which provides a GlobalDashboard feature (https://www.monarc.lu/documentation/user-guide/#global-dashboard), then you need to follow the installation instructions:
https://www.monarc.lu/documentation/technical-guide/#stats-service
