### ISSUE TITLE
Garbled logon screen with Internet Explorer

### ISSUE THREAD

**Issue by Tichod** [monarc-project/MonarcAppFO#328]
**Describe the bug**
When accessing the login screen in Microsoft Internet Explorer, the resulting display is taller than the overall navigator window. The credentials boxes are reachable through the use of the right/vertical movement scrollbar.

**To Reproduce**
0. Update MONARC from 2.9.16 to 2.10.1 (don't know if related, but error appeared after that)
1. Access login screen in Microsoft Internet Explorer.
2. See error on screen copies

**Expected behavior**
The login screen fills in nicely in navigator window, without the need of scrollbar.

**Screenshots**
Cf. attached file.

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 20.04.2
| OS version (client)                   | Win10
| PHP version                             | 7.4.3
| MONARC version / git hash     | 2.10.1 (virtual machine)
| Browser                                    | Internet Explorer 20H2

**Additional context**
*** Accessing the logon screen with Mozilla Firefox, Google Chrome or Microsoft Edge works correctly.
*** With Mozilla Firefox, Google Chrome or Microsoft Edge, the display is garbled differently, only after logging in. I opened a separate report for this : #327
![2021_02_02-MONARC_UI_error-IE_top](https://user-images.githubusercontent.com/18058781/106753448-f8479600-662b-11eb-8509-f9bbc70b458b.png)
![2021_02_02-MONARC_UI_error-IE_bottom](https://user-images.githubusercontent.com/18058781/106753452-f978c300-662b-11eb-8c08-586fe35c27d8.png)

.

**Comment by ruslanbaidan** [comment]
We do not recommend to use Internet Explorer. It can cause some user interface issues.
Could you try to use Mozilla Firefox or Google Chrome.

**Comment by Tichod** [comment]
Thank you.
I do not personally use Internet Explorer.
This was just a test, to see which navigators were concerned by bug report #327.
Login screen is ok with all other navigators.

**Comment by KonzeptAcht** [comment]
The Internetexplorer is also EOL since 2020, so it should generally no longer be used ;)

**Comment by ruslanbaidan** [comment]
> Thank you.
> I do not personally use Internet Explorer.
> This was just a test, to see which navigators were concerned by bug report #327.
> Login screen is ok with all other navigators.

The issue might be related. To detect, it's possible to look at your HTML code in Internet Explorer to see if there is something hidden displayed before the login form.
Might be there are some errors, which are overlapped by the background image.
