### ISSUE TITLE
multiple login sessions per user

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#333]
**Describe the bug**
Since version 2.10.1 it is no longer possible to be logged in with the same user in multiple tabs or windows at the same time. It can be very helpful, especially in large analyses, to make risk assessments or links in one window while the asset library is open in the other one.

**To Reproduce**
1. Login on one Tab
2. Create a new Tab
3. Log in the new tab
4. The session in the old tab is canceled and a new login is necessary

**Expected behavior**
Multiple tabs with the same login are possible at the same time

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04 LTS
| OS version (client)                   | MacOS, Win10, Linux
| PHP version                             | 7.4
| MONARC version / git hash     | 2.10.1
| Browser                                    | Firefox, Chrome, Safari, Opera

**Additional context**
The problem is only present since version 2.10.1 and can be adjusted in the my.monarc environment.

**Comment by ruslanbaidan** [comment]
The fix will cover the scenario when we can open multiple tabs with Monarc application and session will be shared between them.
So no need to login again.

**Comment by ruslanbaidan** [comment]
PR:
https://github.com/monarc-project/ng-client/pull/24/files
