### ISSUE TITLE
translation errors formulas

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#338]
**Describe the bug**
When the interface language was changed to German, the description and the formulas no longer match.

**To Reproduce**
1. Change interface language to german
2. Go to "Evaluation scales" 
3. Scroll down to "Acceptance thresholds of information risks"
4. Compare the legend under the formula with the variables in the formula
5. See error

**Expected behavior**
Conformity of the variables of the legend with the formula.

**Screenshots**
![ITV Bewertungsskala MONARC](https://user-images.githubusercontent.com/47662401/110770508-aeb91f00-8259-11eb-9419-7b05c39cc3ab.PNG)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04 LTS
| OS version (client)                   | MacOS, Win10, Ubuntu
| PHP version                             | 7.4
| MONARC version / git hash     | 2.10.2
| Browser                                    | Firefox, Chrome, Safari

**Comment by ruslanbaidan** [comment]
It seems it was auto generated and replaced by the tool we implemented for the translations.
I updated the letters for the german translations:
https://translate.monarc.lu/translate/monarc/front-office/de/?offset=1&q=i%3A&sort_by=-priority%2Cposition&checksum=

If you would like to change some german translations, we can create an account for you to allow this.

**Comment by KonzeptAcht** [comment]
Thanks for the adjustment. We would be very happy about an access.

**Comment by ruslanbaidan** [comment]
The changes for the translation is already in ng-client master branch, so you need to run `update-all.sh -b` on your servers.
It has been done already on my.monarc.lu.
Sent an invitation to Marc Sparwel.
