### ISSUE TITLE
Error during administrator creation

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#345]
**Describe the bug**
When assigning permissions, it is possible to give the user only the administrator role. However, in this state the user is not able to perform a successful login.

**To Reproduce**
1. Go to User management
2. Create a new User
3. Assign administrator without user permissions
4. Log out the user and log in again with the newly created user

**Expected behavior**
Access to monarc with new user.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47662401/114868937-bf2f5d00-9df6-11eb-92ba-75a972aae19c.png)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Debian, Ubuntu, Centos
| OS version (client)                   | MacOS, Win10, Ubuntu
| PHP version                             | 7.4, 7.3
| MONARC version / git hash     | 2.10.2
| Browser                                    | Firefox, Chrome, Safari

**Additional context**
The error can be reset in the my.monarc instance

Webconsole Error Code:
`Possibly unhandled rejection: {"data":"","status":401,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/stats/validate-stats-availability","headers":{"Accept":"application/json, text/plain, */*","token":"2eafd534f649bf2faca0fab4f085747bfb062aa1ff35363c09af883d0b5c6078302fda7ca5.90488533"},"cached":false},"statusText":"Unauthorized","xhrStatus":"complete","resource":{}}`

**Comment by cedricbonhomme** [comment]
Thank you for the report. The issue is identified and we can provide a fix soon.
If you give CEO role to the admin it should work as a workaround only of course.
