### ISSUE TITLE
Deliverable export broken with attached files

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#376]
**Describe the bug**
If in a text field like the "Risk analysis context" (${CONTEXT_ANA_RISK}) a PDF file is attached, the variable is not taken into account when generating the deliverable word file.

**To Reproduce**
1. Open Step 1: Risk analysis context
2. Attache any file
3. Export deliverable  for Step 1
4. The field where the content of the variable should be inserted remains empty

**Expected behavior**
The attached file will be embedded in the Word or downloaded as a separate file in addition to the report. The text inserted under "Risk analysis context" is displayed normally in the report

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04 LTS
| OS version (client)                   | MacOS, Win10, Ubuntu, Debian
| PHP version                             | 7.4
| MONARC version / git hash     | 2.10.4
| Browser                                    | Firefox, Chrome, Safari

**Additional context**
The error can be reproduced in the my.monarc.

**Comment by cedricbonhomme** [comment]
Hi,

How did you manage (previously?) to attach a file ? It is not supposed to be working/implemented. Maybe by drag-and-drop ?

**Comment by KonzeptAcht** [comment]
Hi,

We have not used the function yet. A trainee has noticed this error. He used the paper clip to upload a pdf file.

![grafik](https://user-images.githubusercontent.com/47662401/132178741-228dedde-8a69-4c65-a622-021fc2782879.png)

**Comment by cedricbonhomme** [comment]
OK, thank you. That is not the intended behaviour but maybe an idea to keep (not necessary via drag and drop in this field). For the moment we will prevent this kind of action.
