### ISSUE TITLE
Update 2.10.4 -> 2.11.0 fails

### ISSUE THREAD

**Issue by Tichod** [monarc-project/MonarcAppFO#379]
**Describe the bug**
I try to update from version 2.10.4 to 2.11.0, using guidance from technical guide (§5.2.1. Update a single MONARC instance)

**To Reproduce**
1. From shell console, under user monarc, I type successively following commands:
`/var/lib/monarc/fo/scripts/update-all.sh -c`
`sudo rm -Rf /var/lib/monarc/fo/data/cache/*`
`sudo systemctl restart apache2.service`
2. No error message in console
3. When logged in web frontend, version appears to be 2.10.4, and new functionalities not present (having the possibility to define custom scales for operational risks, introduction of the risk context and the risk owner)

**Expected behavior**
I expect to read version 2.11.0 in left pannel of web frontend, and observe new functionalities.

**Screenshots**
No screensho necessary, I think.

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04.4
| OS version (client)                   | Win10
| PHP version                             | 7.4.23
| MONARC version / git hash     | 2.10.4 (virtual machine)
| Browser                                    | Firefox

**Additional context**
N/A

**Comment by KonzeptAcht** [comment]
Hello @Tichod,

in the installation directory of MONARC (by default /var/lib/monarc/fo/), is the version 2.11.0 specified in the "VERSION.json" or is the 2.10.4 still referenced here as well?

Best regards

Marc

**Comment by cedricbonhomme** [comment]
Hello,

Could you please give us the following information ?

- the result of ``git status`` executed at the root of the project;
- the result of ``git log -n 5`` executed at the root of the project;
- last (6 is normally enough) records of the phinxlog table for the datababe monarc_cli;
- last (6 is normally enough) lines of ``ls -l vendor/monarc/frontoffice/migrations/db/``;
- the result of the command ``composer up`` executed at the root of the project.

**Comment by Tichod** [comment]
I'm sorry for my late reply.
@KonzeptAcht: version mentionned in `VERSION.json` = 2.10.4
@cedricbonhomme: file hereunder
[commands.txt](https://github.com/monarc-project/MonarcAppFO/files/7162575/commands.txt)
Thank you!

**Comment by cedricbonhomme** [comment]
The code is not up-to-date.

There was probably an issue at the beginning with the script ``./scripts/update-all.sh``.
It could be an issue with composer or Git, etc.

Could you please provide us the output of:

```bash
$ ./scripts/update-all.sh
```

thank you.

Especially the beginning (or everything if easier for you).

**Comment by Tichod** [comment]
**Update finally worked!**
Until now, I typed `./upgrade-all.sh -c` from within `/var/lib/monarc/fo/scripts/`, instead of `./scripts/upgrade-all.sh -c` from within `/var/lib/monarc/fo/`.
==> I'll make a quick script, instead of typing erroneous commands.

I'm sorry for your waste of time. PEBKAC, I'm afraid, with myself on the chair.

Please close ticket.

**Comment by cedricbonhomme** [comment]
;-)
No worry !
