### ISSUE TITLE
Statement of applicability

### ISSUE THREAD

**Issue by lunelt** [monarc-project/MonarcAppFO#401]
Hi I started to use work with Monarc FO
and after I installed the image .ova I noticed the I missed 
all the HOME, users, administrators etccc
the second problem is in statement of applicability, after I select the referential the code is not clickable. 

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                  | Ubuntu18.04, 
| OS version (client)                   | Win10,
| PHP version                             | 7.4.12
| MONARC version / git hash     | v2.11.1 hash of the commit
| Browser                                    | Chrome

**Additional context**

**Comment by lunelt** [comment]
![Capture d’écran (180)](https://user-images.githubusercontent.com/94697094/142645695-2edd64b6-dbd6-4c57-907d-1f67e7acd419.png)

**Comment by KonzeptAcht** [comment]
Hello lunelt,
can you explain the first problem in more detail? Here I think a little background knowledge is missing. On the topic of SOA, only references are clickable that were referenced in the risk analysis.

**Comment by jerolomb** [comment]
Hello, 

I don't really understand your first issue, but on your screenshot, i see you are administrator and you can create other users and admin. Is it the issue ? 

For the second part, you have no risks in your risk analysis so the code in the SOA is not clickable (no risks to link).

You can also find the doc here : https://www.monarc.lu/documentation/user-guide/

**Comment by lunelt** [comment]
> Also, your screenshot still points to 2.11.0, are you sure you are using 2.11.1?

yes it is 2.11.0

**Comment by lunelt** [comment]
I cannot see Home>My Analysis

**Comment by KonzeptAcht** [comment]
Have you tried another browser like Firefox or Chrome?

**Comment by lunelt** [comment]
> 



> Have you tried another browser like Firefox or Chrome?

I'am using chrome

**Comment by ruslanbaidan** [comment]
I would recommend to use the latest image first: https://vm.monarc.lu/latest/
In v2.11.1 there is no issue for sure.

**Comment by jerolomb** [comment]
Your're right it's not on your screenshot. It's more clear, it's maybe a cache issue, can you try ctrl+f5 to refresh the page ?

**Comment by lunelt** [comment]
Thank you
How I can download from https://vm.monarc.lu/latest/? Plaese

Le ven. 19 nov. 2021 à 16:32, Ruslan Baidan ***@***.***> a
écrit :

**Comment by KonzeptAcht** [comment]
Only click on the first listed file (MONARC_v2.11.1@7ce775fcd8e6d44be0fbce4d783e7cc6b0fc77ea.ova)

**Comment by ruslanbaidan** [comment]
Actually it opens the content in Chrome, I'll correct it.
For now click with the right button and select "save link as".

**Comment by lunelt** [comment]
ctrl+F5 Nothing change

**Comment by lunelt** [comment]
Thank you

Le ven. 19 nov. 2021 à 16:39, Ruslan Baidan ***@***.***> a
écrit :

**Comment by ruslanbaidan** [comment]
The download of ".ova" files is now started automatically.

**Comment by lunelt** [comment]
Thank you now it is ok

Le ven. 19 nov. 2021 à 16:49, Ruslan Baidan ***@***.***> a
écrit :
