### ISSUE TITLE
Deletion of snapshot fails

### ISSUE THREAD

**Issue by lva** [monarc-project/MonarcAppFO#428]
The deletion of a snapshot fails.
The error "Anr id error" is displayed.

I'm using the v. 2.11.1 Monarc virtual machine.

How to reproduce:

1. Create a snapshot
2. Try to delete the snapshot

**Comment by ruslanbaidan** [comment]
The Monarc image of version 2.11.1 was not up to date, so it was re-uploaded. The hash is changed.
Could you please download and use the latest image: https://vm.monarc.lu/latest/
