### ISSUE TITLE
Empty risk analysis source

### ISSUE THREAD

**Issue by fastfire** [monarc-project/MonarcAppFO#43]
When I try to add a new risk analysis I find follow situation and I can not do anything:

![image](https://user-images.githubusercontent.com/16737186/33004994-0b6ba6d0-cdc4-11e7-955e-6d20783a2231.png)

**Comment by cedricbonhomme** [comment]
Hi,

Models are missing. Did you import both database ?
https://github.com/monarc-project/MonarcAppFO/blob/master/vagrant/bootstrap.sh#L208

**Comment by fastfire** [comment]
Hi Cedric, now work, thank you very much!

But... an other question: I followed install doc in monarc/INSTALL/INSTALL.ubuntu1704.md e don't find doumentation about this import database... it is correct?

**Comment by cedricbonhomme** [comment]
Indeed, this install guide is not 100% up-to-date. This changes few days ago, because we are currently improving the database (#7). I advise you to use the vagrant bootstrap.sh file as reference. It is kept up-to-date.
You can also use the monarc-packer repo to build a VM. Should be working fine.
