### ISSUE TITLE
Monarc token login

### ISSUE THREAD

**Issue by fastfire** [monarc-project/MonarcAppFO#44]
Hi,

is possibile to use a login token to login in in Monarc? I would like to use my intranet login to automate login in Monarc.

Thank you!

**Comment by cedricbonhomme** [comment]
We should consider this. Indeed, some organizations are actually using MONARC in their intranet.

**Comment by fastfire** [comment]
And these organization use the same credential login for intranet and Monarc too or different?

**Comment by cedricbonhomme** [comment]
They are using different logins, as far as I know.

Bigger organizations are using MONARC like this: http://monarc.lu/technical-guide/#global-architecture (with several instances of MONARC font offices)

**Comment by jfrocha** [comment]
Related to #22

**Comment by ruslanbaidan** [comment]
Duplication with single sign-in and LDAP
