### ISSUE TITLE
Monarc translate

### ISSUE THREAD

**Issue by fastfire** [monarc-project/MonarcAppFO#45]
Hi,

I would like to translate Monarc in Italian language. It is possibile?

Thank you!

**Comment by cedricbonhomme** [comment]
Hi,

That would be really great. As you may have realized MONARC is already available in 4 languages. It would be really cool to also have MONARC also available in Italian.

As I told you in a previous message, we are actually working on some database improvements:
https://github.com/monarc-project/MonarcAppFO/issues/7
One of the main goal is to manage translations in a better way, by having a proper translation table (see #7). We are supposed to have this soon.

So we would of course accept a translation to Italian after theses improvements.

**Comment by jfrocha** [comment]
Related to #7
