### ISSUE TITLE
Missing labels

### ISSUE THREAD

**Issue by dbarzin** [monarc-project/MonarcAppFO#462]
**Describe the bug**
Some labels are missing in the latest Monarc OVA (2.12.3)

**To Reproduce**
1. Download and install the last Monarc OVA
2. Login and create a new analysis

**Expected behavior**
Complete messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/43208232/195352698-31222b34-44c9-4f5b-84d4-80bc1c142ee1.png)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu
| OS version (client)                   | Win10
| PHP version                             | N/A
| MONARC version / git hash     | 2.12.3
| Browser                                    | Firefox

**Additional context**
N/A

**Comment by ruslanbaidan** [comment]
There is no issue with the .ova.
There was a javascript library update (responsible for langs and flags) that could be the explanation of your issue.
One of the possible situations:
1. Cache issue. Open the web app in different browser, clean cache in the current window or open in an incognito tab.
2. The previous application is still active/launched in your VirtualBox and it was opened.
