### ISSUE TITLE
Invalid password

### ISSUE THREAD

**Issue by dbarzin** [monarc-project/MonarcAppFO#493]
**Describe the bug**
Could not login after manual installation of Monarc.
Error on the login page "Your e-mail or password is invalid, please try again."

**To Reproduce**
1. Go to login page : http;//127.0.0.1
2. Click user: admin@admin.localhost password: admin click "Log in"

**Expected behavior**
Successful login

**Screenshots**

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 22.04
| OS version (client)                   | Win10
| PHP version                             | 8.0
| MONARC version / git hash     | release v2.12.6
| Browser                                    | Chrome

**Additional context**
No error present in the Apache error.log
The user is present in the database

**Comment by dbarzin** [comment]
I have found an error in the web console : "Access denied for user  'root'@'localhost'"

**Comment by ruslanbaidan** [comment]
Would it be possible for you to install php v8.1 and retry ?
Otherwise we can investigate the problem on v8.0 later.

**Comment by dbarzin** [comment]
I finally get it to work with PHP 8.1 and Ubuntu 22.04.
I will provide a installation procedure.
Thanks,
Didier

**Comment by ruslanbaidan** [comment]
Thank you for letting us know.
I'm going to validate the issue with php8.0 later.

**Comment by dbarzin** [comment]
The objective is not to get it to work with several PHP versions but with a good one.

**Comment by dbarzin** [comment]
After this change, I got another error : 

angular-common-libs.js:132  Possibly unhandled rejection: {"data":{"errors":[{"message":"Monarc\\Core\\Service\\PasswordService::changePassword(): Argument #3 ($newPassword) must be of type string, null given, called in /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/monarc/frontoffice/src/Controller/ApiUserPasswordController.php on line 37","error":"error-exception","exception":{"class":"TypeError","file":"/var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/monarc/core/src/Service/PasswordService.php","line":123,"message":"Monarc\\Core\\Service\\PasswordService::changePassword(): Argument #3 ($newPassword) must be of type string, null given, called in /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/monarc/frontoffice/src/Controller/ApiUserPasswordController.php on line 37","stacktrace":"#0 /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/monarc/frontoffice/src/Controller/ApiUserPasswordController.php(37): Monarc\\Core\\Service\\PasswordService->changePassword()\n#1 /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(431): Monarc\\FrontOffice\\Controller\\ApiUserPasswordController->update()\n#2 /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/laminas/laminas-eventmanager/src/EventManager.php(320): Laminas\\Mvc\\Controller\\AbstractRestfulController->onDispatch()\n#3 /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\\EventManager\\EventManager->triggerListeners()\n#4 /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(105): Laminas\\EventManager\\EventManager->triggerEventUntil()\n#5 /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(306): Laminas\\Mvc\\Controller\\AbstractController->dispatch()\n#6 /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/laminas/laminas-mvc/src/DispatchListener.php(117): Laminas\\Mvc\\Controller\\AbstractRestfulController->dispatch()\n#7 /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/laminas/laminas-eventmanager/src/EventManager.php(320): Laminas\\Mvc\\DispatchListener->onDispatch()\n#8 /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\\EventManager\\EventManager->triggerListeners()\n#9 /var/lib/monarc/releases/MonarcAppFO-v2.12.6/vendor/laminas/laminas-mvc/src/Application.php(319): Laminas\\EventManager\\EventManager->triggerEventUntil()\n#10 /var/lib/monarc/releases/MonarcAppFO-v2.12.6/public/index.php(34): Laminas\\Mvc\\Application->run()\n#11 {main}"}}]},"status":500,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/user/password/1","data":{"old":"admin"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","token":"0f866b00663814b5e3bad76589cfb7c028c7deda85d81abe9d636cb8b5a40146479e338865014890138518.00407476"},"cached":false},"statusText":"Internal Server Error","xhrStatus":"complete"}
