### ISSUE TITLE
Composer: Enhance dependencies management

### ISSUE THREAD

**Issue by xplodwild** [monarc-project/MonarcAppFO#5]
Currently, the MonarcAppFO/MonarcAppBO repositories (which basically are skeletons) contains all the required dependencies for the entire app, including the ones that are actually only required by the zm_core/zm_[client|backoffice] repositories.
Dependencies should be atomic, and the skeletons should only contain dependencies on zm_client or zm_backoffice, which in turn should depend on zm_core and other dependencies.

**Comment by ruslanbaidan** [comment]
It had been continuously improved from the version 2.9.1 to 2.10.1.
As far as we have plans to reorganise the projects structure, it might make no sense to look at any further improvement on this point.
