### ISSUE TITLE
WSL Installation fails Error: Could not import 'runserver'.

### ISSUE THREAD

**Issue by mmentges** [monarc-project/MonarcAppFO#541]
**Describe the bug**
I tried to install MonarcFO using WSL https://github.com/monarc-project/MonarcAppFO/tree/master/wsl

**To Reproduce**
1. Executing "curl -sSL https://raw.githubusercontent.com/monarc-project/MonarcAppFO/master/wsl/installFO.sh | bash"
2. See error

```
--- Installing the stats service… ---

 

Error: Could not import 'runserver'.

 

Usage: flask [OPTIONS] COMMAND [ARGS]...

Try 'flask --help' for help.

 

Error: No such command 'db_create'.

Error: Could not import 'runserver'.

 

Usage: flask [OPTIONS] COMMAND [ARGS]...

Try 'flask --help' for help.

 

Error: No such command 'db_init'.

Error: Could not import 'runserver'.

 

Usage: flask [OPTIONS] COMMAND [ARGS]...

Try 'flask --help' for help.

 

Error: No such command 'client_create'.

Error: Could not import 'runserver'.

 

Usage: flask [OPTIONS] COMMAND [ARGS]...

Try 'flask --help' for help.

 

Error: No such command 'client_create'.
```

**Expected behavior**
Complete installation with a running MonarcFO

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 22.04.3 LTS
| OS version (client)                   | Windows 10 Business 22H2
| Browser                                    | Chrome

**Additional context**
When attempting to open http://localhost it just responds with a blank page, but I can see the Monarc Icon in the chrome tab. But no login screen.

**Comment by ruslanbaidan** [comment]
The WSL instructions are not for Ubuntu and only for the development purposes.
We are not maintaining them.
If you would like to develop Monarc (change or extend the code base) on your Windows machine, you could 1st contribute to the WSL docs to define a working installation scenario.
Thank you.
