### ISSUE TITLE
linked assets can no longer be deleted after update to 2.13.1

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#545]
**Describe the bug**
Assets that are linked to other objects in the asset library can no longer be deleted in 2.13.1. The window which in previous versions offered the option to remove a link or force deletion is no longer opening:

![image](https://github.com/user-attachments/assets/e937620b-e1a5-43eb-bb80-a67fa8b45b35)

**To Reproduce**
1. Create two assets in the asset library
2. Link the two assets together in the asset library
3. Try to delete one of the two assets
4. Error message in the web console

The error can be reproduced in the my.monarc instance.

**Expected behavior**
Display the confirmation window for deleting the asset and removing the link

![image](https://github.com/user-attachments/assets/261244b5-85ef-4802-93cf-5a129c6bd934)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 22.04 LTS
| OS version (client)                   | Arch Linux, macOS, Windows 10
| PHP version                             | 8.1, 8.2
| MONARC version / git hash     | 2.13.1
| Browser                                    | Firefox, Chrome, Safari

**Comment by ruslanbaidan** [comment]
Thank you for the report.
The fix is done and is going to be deployed as a patch:
https://github.com/monarc-project/zm-client/releases/tag/v2.13.1-p1

**Comment by ruslanbaidan** [comment]
The fix was deployed
