### ISSUE TITLE
Evaluation of trends and threats

### ISSUE THREAD

**Issue by ThierryPGT** [monarc-project/MonarcAppFO#59]
Hello Team CASES,
It's impossible to evaluate the thread (1 --> 4) that will be used in the risk analysis.
<img width="543" alt="threats" src="https://user-images.githubusercontent.com/26403448/34431743-dd22f46e-ec71-11e7-828a-e48eb99fa27e.png">
CU
Thierry

**Comment by jerolomb** [comment]
Hello Thierry,

Do you ticked the case of the method in the step 1 : "Definition des critères d'évaluation des risques" ?

If you don't tick this case, you normally don't define your scale so you can't evaluate with the scale.  

Jérôme

**Comment by ThierryPGT** [comment]
Hello Jérôme,
A little strange, but it's better like that.
Thierry
