### ISSUE TITLE
Licensing issues - copyright mentions to be modified

### ISSUE THREAD

**Issue by matthieu-farcot** [monarc-project/MonarcAppFO#63]
Hi

Many files included in the ZM related projects include a mention "Copyright (c) Cases" which should be modified and replaced by a mention "Copyright (c) 2018 SMILE GIE Securitymadein.lu - Licensed under GNU Affero GPL v3" (without the quotes).

Such files are:
a) 71 mentions in zm-backoffice (to be found in zm-backoffice/src/MonarcBO)
b) 333 mentions in zm-client (to be found in zm-client/src/MonarcFO)
c) 295 mentions in zm-core  (to be found in zm-core/src/MonarcCore)

To be corrected.

Thanks,

Matthieu

**Comment by cedricbonhomme** [comment]
thanks, working on it !
