### ISSUE TITLE
Where do we find NewCenturySchlbk-Roman font in Ubuntu Package?

### ISSUE THREAD

**Issue by StarAurryon** [monarc-project/MonarcAppFO#66]
Hello,

I'm not finding the font NewCenturySchlbk-Roman that is used to generate reports. Where can I find this font on Ubuntu packages? I'm currently building a docker container.

Thanks in advance

**Comment by StarAurryon** [comment]
I just found out. It is the gsfonts package. You can close the issue.

**Comment by cedricbonhomme** [comment]
Cool! Let us know if you have a working docker container for MONARC. Maybe we can also use it.

Thank you
