### ISSUE TITLE
Incorrect project name in Word export after rename

### ISSUE THREAD

**Issue by gjherbiet** [monarc-project/MonarcAppFO#68]
After renaming a project, the Word export still uses the original project name.

Steps to reproduce:

1. Create a risk analysis with "Name A"
2. Rename project to "Name B"
3. Generate a deliverable (e.g. "Context validation")
4. Generated Word document still uses the original "Name A" project name.

**Comment by cedricbonhomme** [comment]
Actually the project name (name of the analysis) is not in the report. As far as I know. There is the document name. And the document name can be configured just before the generation of the report.

Can you precise at which page you have the problem? The first one ?

**Comment by gjherbiet** [comment]
On the cover page the main title, also referred to as "Company" in the "General Information" block.

**Comment by cedricbonhomme** [comment]
OK, I got it. The value of "Company" is editable for an admin and you are not admin on the formation instance. If you were an admin of your instance you would be able to change this here:

![screenshot_20180309_080606](https://user-images.githubusercontent.com/465400/37194990-3d584f24-2371-11e8-98e2-c73a31f89d32.png)

Also, the fact that lot of people yesterday named their analysis (project) "MyPrint" is even more confusing. Like in my screen shot in the left panel :-)

At first I thought that you were talking about the name of the document. Also displayed on the first page, and you can change this value just before the generation of the report.
