### ISSUE TITLE
Header icons missing in deliverable Evaluation and treatment of risks 

### ISSUE THREAD

**Issue by cudeso** [monarc-project/MonarcAppFO#72]
The icon in the header section of the deliverable (Word) are missing, starting from section 4.2 Risk treatment. Headers in pages before that section contain the icon.
![screenshot_08_03_2018__14_54](https://user-images.githubusercontent.com/256028/37154563-b6db740c-22e0-11e8-8d89-92580cfc4a79.jpg)

**Comment by cedricbonhomme** [comment]
I guess you are using a Mac? I am not available to reproduce this bug.
We have to investigate this with Apple users. Maybe it is a template issue.

**Comment by cudeso** [comment]
The same problem exists with LibreOffice 5.1.6.2 on Ubuntu.

**Comment by cedricbonhomme** [comment]
Mmm strange, working on my kubuntu with LibreOffice version 5.4.5.1

**Comment by cedricbonhomme** [comment]
Also with version 5.6, same problem.
