### ISSUE TITLE
Library of default recommendations

### ISSUE THREAD

**Issue by adulau** [monarc-project/MonarcAppFO#75]
It would be nice to provide a library with a list of default recommendations in MONARC.

There are some examples in existing MISP galaxies like [Preventive Measure](https://www.misp-project.org/galaxy.html#_preventive_measure) - [JSON](https://github.com/MISP/misp-galaxy/blob/master/clusters/preventive-measure.json) maybe related to @cedricbonhomme works on common libraries.

**Comment by cedricbonhomme** [comment]
thanks this will be in the repository (ideally all related JSON files will be)

**Comment by jfrocha** [comment]
Feature deployed on [2.9.0](https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.9.0) release and improved in the following releases
