### ISSUE TITLE
Testing PHPWord new version

### ISSUE THREAD

**Issue by adulau** [monarc-project/MonarcAppFO#79]
Could we test the recent version of PHPWord? And see if this one works versus the forked (and unmaintained) version of PHPWord used in MONARC? Maybe additional export would be great (e.g. OOXML)?

**Comment by cedricbonhomme** [comment]
I'll have a look. I forgot this: monarc-project/monarc_phpword#1
In fact we are not so far from the upstream repository (considering stable releases). I'll check more in details our local changes and their actual usefulness.
