### ISSUE TITLE
Compare delta between two analysis/snapshot

### ISSUE THREAD

**Issue by BenjaminJoly** [monarc-project/MonarcAppFO#80]
A proposition made during the training of March 2018, but we could have a view that can show differences between two analyses (to compare impact/probability/qualification, assets, why not even more).

This way, it should be possible to that two security consultant can compare their work. It can also be used to compare differences between two snapshots, to quickly see what has changed.

**Comment by jerolomb** [comment]
It's planned in the roadmap https://github.com/monarc-project/MonarcAppFO/wiki/dashboard_frontend_specs

**Comment by jfrocha** [comment]
Global Dashboard, release [2.10.1](https://github.com/monarc-project/MonarcAppFO/releases/tag/v2.10.1)
