### ISSUE TITLE
Inconsistency of Threat and Vulnerability Tables

### ISSUE THREAD

**Issue by ThierryPGT** [monarc-project/MonarcAppFO#82]
Hello,
in the third deliverable, Threat and Vulnerability Tables in chapters 5.2.2 and 5.2.3 are inconsistent according to changes made in the knowledge database (It seems that they are always the same)
CU
Thierry

**Comment by jerolomb** [comment]
Hi Thierry,

Can you precise your issue ? And tell us which version of MONARC you are using ? 

C U 

Jérôme

**Comment by ThierryPGT** [comment]
Hi Jérome,

 

On the Cloud

 

This is what the deliverable contains 



 

This is what the database contains

 



 

Thierry Petitgenet

**Comment by jerolomb** [comment]
Strange, working fine for me, can you tell us what's the language of the analysis ?

**Comment by ThierryPGT** [comment]
French … 

I will create a risk analysis with this issue and I’ll give you write on it.

It’s easier.

CU

 

Thierry Petitgenet
