### ISSUE TITLE
Provided OVA file does not Work on VMWare

### ISSUE THREAD

**Issue by eLvErDe** [monarc-project/MonarcAppFO#90]
Hello,

I tried to import the OVA file into our vCenter 6.5 server and it failed:
![2018_05_17_09_42_25_vsphere_web_client](https://user-images.githubusercontent.com/1586757/40174690-2073f2aa-59d6-11e8-81df-a5325c6d76cf.png)

According to VitualBox issues, OVA generated by VirtualBox are just crap and it seems they don't care about fixing it (bug is 7 years old):
https://www.virtualbox.org/ticket/7982

So here is how I managed to get it imported into VMWare.

1. Get ofvtool to sanitize the improper definition (you need a VMWare account):
https://www.vmware.com/support/developer/ovf/

2. Sanitize the file with ovftool
`ovftool --lax MONARC_demo.ova MONARC_demo_ovftool_lax.ova`

3. Hardware requirements are still incorrect and ask for stuff VMWare cannot provide. Inspired by some code grabbed on VirtualBox ticket, I made the following script to fix hardware definition inside the OVA file:

```
#!/usr/bin/python3
#
# usage:
#        conv2vmx-ovf.py some-vm.ovf
#
# ref: http://www.cnblogs.com/eshizhan/p/3332020.html
#

import sys
fn = sys.argv[1]
fp = open(fn, 'rb').read()

fp = fp.replace(b'<vssd:VirtualSystemType>virtualbox-2.2', b'<vssd:VirtualSystemType>vmx-07')

fp = fp.replace(b'<rasd:Caption>ideController', b'<rasd:Caption>scsiController')
fp = fp.replace(b'<rasd:Description>IDE Controller', b'<rasd:Description>SCSI Controller')
fp = fp.replace(b'<rasd:ElementName>ideController', b'<rasd:ElementName>scsiController')
fp = fp.replace(b'<rasd:ResourceSubType>PIIX4', b'<rasd:ResourceSubType>lsilogic')
fp = fp.replace(b'<rasd:ResourceType>5', b'<rasd:ResourceType>6')

nfp = open('vmx_' + fn, 'wb')
nfp.write(fp)
```
Run the script against the file generated by ovftool and import the resulting file (prefixed with vmx_) and your good to go.

I'm not sure how you should sort this out but your OVA file is definitely inteded to be compatible with ESX. I'd suggest trying to apply this howto on your released file and see if it still works in VBox, if so, I'd apply this before each release...

But anyway, it still fails to start, not finding a bootloader on the provided hard disk... I have no clue what's going on but could you at least provide another way to install MONARC ?

Best regards, Adam.

**Comment by cedricbonhomme** [comment]
Hello,

thank you for your feedback.

We are aware of this problem with VMWare.

Actually our [packer deployment script](https://github.com/monarc-project/monarc-packer/) is only ready for VirtualBox. The cleanest solution for us is to improved it by adding a way to generate both VMWare and VirtualBox compatible machines. I think this is what we should do.

An other way to install MONARC is to follow [the instructions](https://github.com/monarc-project/MonarcAppFO/blob/master/INSTALL/INSTALL.ubuntu1704.md) or to use the corresponding [bootstrap script](https://github.com/monarc-project/monarc-packer/blob/master/scripts/bootstrap.sh) used by packer.
