### ISSUE TITLE
Table of interview

### ISSUE THREAD

**Issue by ThierryPGT** [monarc-project/MonarcAppFO#91]
Hello,
when you export/import a rsk analysis, the table of interview is not exported.
CU
Thierry

**Comment by cedricbonhomme** [comment]
hello,

thank you for the feedback. I think this is a good ideq. We'll keep you informed about that.

**Comment by cedricbonhomme** [comment]
It is indeed. You must set 'Export with assessments?' to yes.

**Comment by cedricbonhomme** [comment]
I close it, since it seems to be a choice.
