### ISSUE TITLE
Removal of a Recommandation on same risk of different Asset of the same type

### ISSUE THREAD

**Issue by ThierryPGT** [monarc-project/MonarcAppFO#92]
Hello Team CASES,

I finally identified the cause of an issue on recommandations that bothering me since version 2 of MONARC.
If you attached the same recommandation, of the same risk of 2 differents assets of the same type, when you detach the recommandation of one of them, it desappear on the second (or all) of one .
See the 3 pictures attached in order

CU
Thierry
![1-reco](https://user-images.githubusercontent.com/26403448/40583821-1fd1b45a-6196-11e8-8ac8-86d419b1d018.JPG)
![2-reco](https://user-images.githubusercontent.com/26403448/40583824-22da7f88-6196-11e8-9605-5440aa8de24b.JPG)
![3-reco](https://user-images.githubusercontent.com/26403448/40583825-255cd7ce-6196-11e8-968a-03a42e9c84eb.JPG)

**Comment by ThierryPGT** [comment]
Hello,
Is the cloud up to date ? If yes, this isssue is not solved.
Sorry
Thierry

**Comment by cedricbonhomme** [comment]
the cloud is not updated.
