### ISSUE TITLE
Operational risks are not updated

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#93]
When we change something in the knowledge base the operational risks are not updated

**Comment by jerolomb** [comment]
It remains to make a phinx script to correct the issue on the old imported analysis

**Comment by jerolomb** [comment]
The following sql request would worked by DB 

```
update instances_risks_op set instances_risks_op.rolf_risk_id = (
select distinct(rolf_risks.id) from rolf_risks_tags, rolf_risks, objects
where rolf_risks.label1 = instances_risks_op.risk_cache_label1 
and objects.rolf_tag_id = rolf_risks_tags.rolf_tag_id
and rolf_risks_tags.rolf_risk_id = rolf_risks.id
and objects.id = instances_risks_op.object_id
) 
```

**Comment by jerolomb** [comment]
And this one, for the case of rolf_tag_id is missing to : 
update instances_risks_op set instances_risks_op.rolf_risk_id = (
select distinct(rolf_risks.id) from  rolf_risks
where (rolf_risks.label1 = instances_risks_op.risk_cache_label1 OR rolf_risks.label2 = instances_risks_op.risk_cache_label2
OR rolf_risks.label3 = instances_risks_op.risk_cache_label3 OR rolf_risks.label4 = instances_risks_op.risk_cache_label4  )
and instances_risks_op.anr_id = rolf_risks.anr_id
)

**Comment by jfrocha** [comment]
This query could be usefull for specific cases:

`update instances_risks_op set instances_risks_op.rolf_risk_id = (
                        select distinct(rolf_risks.id) from  rolf_risks
                        where (
                           (rolf_risks.label1 = instances_risks_op.risk_cache_label1 AND rolf_risks.label1 IS NOT NULL) 
                        OR (rolf_risks.label2 = instances_risks_op.risk_cache_label2 AND rolf_risks.label2 IS NOT NULL)
                        OR ( rolf_risks.label3 = instances_risks_op.risk_cache_label3 AND rolf_risks.label3 IS NOT NULL) 
                        OR (rolf_risks.label4 = instances_risks_op.risk_cache_label4 AND rolf_risks.label4 IS NOT NULL)
                          )
                        AND instances_risks_op.anr_id = rolf_risks.anr_id AND instances_risks_op.rolf_risk_id IS NOT NULL
                        LIMIT 1
			)`
