### ISSUE TITLE
Improvement the go back from risk sheet

### ISSUE THREAD

**Issue by jfrocha** [monarc-project/MonarcAppFO#95]
Saving number page when go back from risk sheet.
See https://github.com/monarc-project/ng-anr/blob/ddc4e7637e8dd3ef4c52cc26ede87c2cd700d4e6/src/AnrLayoutCtrl.js#L70

**Comment by cedricbonhomme** [comment]
so it seems to be fixed?

**Comment by jfrocha** [comment]
Not at all, I fixed only go back from operational risk sheet to main operational risk table without save last number page.
